Repository COS301-SE-2023/FridgeToPlate, pull requests merged in 2023-05, with the labels that each got.

#11 Setup Workflows
  .github/workflows/ci-dev.yml
  .github/workflows/ci-prod.yml
  .gitignore
  apps/api/build.gradle
  apps/app/sonar-project.properties
  package.json
Labels: dev-ops

#28 Core Setup
  .github/workflows/ci-dev.yml
  .gitignore
  apps/api/build.gradle
  apps/app/project.json
  apps/app/src/app/app.component.html
  apps/app/src/app/app.component.ts
  apps/app/src/app/app.module.ts
  apps/app/src/index.html
  apps/app/src/main.ts
  apps/app/src/styles.scss
  apps/app/src/theme/variables.scss
  apps/app/tailwind.config.js
  libs/app/core/.eslintrc.json
  libs/app/core/README.md
  libs/app/core/jest.config.ts
  libs/app/core/project.json
  libs/app/core/src/core.module.ts
  libs/app/core/src/core.routing.ts
  libs/app/core/src/core.shell.html
  libs/app/core/src/core.shell.scss
  libs/app/core/src/core.shell.spec.ts
  libs/app/core/src/core.shell.ts
  libs/app/core/src/index.ts
  libs/app/core/src/nx-welcome.component.ts
  libs/app/core/src/test-setup.ts
  libs/app/core/tsconfig.json
  libs/app/core/tsconfig.lib.json
  libs/app/core/tsconfig.spec.json
  nx.json
  package-lock.json
  package.json
  tsconfig.base.json
Labels: enhancement

#30 Setup Workflows CD
  .github/workflows/cd-dev.yml
  .github/workflows/cd-prod.yml
  .github/workflows/ci-dev.yml
  .github/workflows/ci-prod.yml
  README.md
Labels: dev-ops

#33 Profile Page Mock Implementation
  .github/workflows/cd-dev.yml
  .github/workflows/cd-prod.yml
  .github/workflows/ci-dev.yml
  .github/workflows/ci-prod.yml
  .gitignore
  README.md
  apps/api/build.gradle
  apps/app/project.json
  apps/app/src/app/app.component.html
  apps/app/src/app/app.component.ts
  apps/app/src/app/app.module.ts
  apps/app/src/index.html
  apps/app/src/main.ts
  apps/app/src/styles.scss
  apps/app/src/theme/variables.scss
  apps/app/tailwind.config.js
  libs/app/core/.eslintrc.json
  libs/app/core/README.md
  libs/app/core/jest.config.ts
  libs/app/core/project.json
  libs/app/core/src/core.module.ts
  libs/app/core/src/core.routing.ts
  libs/app/core/src/core.shell.html
  libs/app/core/src/core.shell.scss
  libs/app/core/src/core.shell.spec.ts
  libs/app/core/src/core.shell.ts
  libs/app/core/src/index.ts
  libs/app/core/src/nx-welcome.component.ts
  libs/app/core/src/test-setup.ts
  libs/app/core/tsconfig.json
  libs/app/core/tsconfig.lib.json
  libs/app/core/tsconfig.spec.json
  libs/app/profile/feature/.eslintrc.json
  libs/app/profile/feature/README.md
  libs/app/profile/feature/jest.config.ts
  libs/app/profile/feature/project.json
  libs/app/profile/feature/src/index.ts
  libs/app/profile/feature/src/profile.module.ts
  libs/app/profile/feature/src/profile.page.html
  libs/app/profile/feature/src/profile.page.scss
  libs/app/profile/feature/src/profile.page.spec.ts
  libs/app/profile/feature/src/profile.page.ts
  libs/app/profile/feature/src/profile.routing.ts
  libs/app/profile/feature/src/test-setup.ts
  libs/app/profile/feature/tsconfig.json
  libs/app/profile/feature/tsconfig.lib.json
  libs/app/profile/feature/tsconfig.spec.json
  nx.json
  package-lock.json
  package.json
  tsconfig.base.json
Labels: enhancement

#40 Login page
  apps/app/src/assets/Logo.png
  libs/app/core/src/core.module.ts
  libs/app/core/src/core.routing.ts
  libs/app/login/feature/.eslintrc.json
  libs/app/login/feature/README.md
  libs/app/login/feature/jest.config.ts
  libs/app/login/feature/project.json
  libs/app/login/feature/src/index.ts
  libs/app/login/feature/src/login.module.ts
  libs/app/login/feature/src/login.page.html
  libs/app/login/feature/src/login.page.scss
  libs/app/login/feature/src/login.page.spec.ts
  libs/app/login/feature/src/login.page.ts
  libs/app/login/feature/src/login.routing.ts
  libs/app/login/feature/src/test-setup.ts
  libs/app/login/feature/tsconfig.json
  libs/app/login/feature/tsconfig.lib.json
  libs/app/login/feature/tsconfig.spec.json
  package-lock.json
  tsconfig.base.json
Labels: enhancement

#37 Create Feature for Demo One
  libs/app/core/src/core.module.ts
  libs/app/core/src/core.routing.ts
  libs/app/create/.eslintrc.json
  libs/app/create/README.md
  libs/app/create/feature/.eslintrc.json
  libs/app/create/feature/README.md
  libs/app/create/feature/jest.config.ts
  libs/app/create/feature/project.json
  libs/app/create/feature/src/create.module.ts
  libs/app/create/feature/src/create.page.html
  libs/app/create/feature/src/create.page.scss
  libs/app/create/feature/src/create.page.spec.ts
  libs/app/create/feature/src/create.page.ts
  libs/app/create/feature/src/create.routing.ts
  libs/app/create/feature/src/index.ts
  libs/app/create/feature/src/test-setup.ts
  libs/app/create/feature/tsconfig.json
  libs/app/create/feature/tsconfig.lib.json
  libs/app/create/feature/tsconfig.spec.json
  libs/app/create/jest.config.ts
  libs/app/create/project.json
  libs/app/create/tsconfig.json
  libs/app/create/tsconfig.lib.json
  libs/app/create/tsconfig.spec.json
  package-lock.json
  package.json
  tsconfig.base.json
Labels: enhancement

#42 💄 (app) Fixed Styling
  libs/app/signup/feature/src/signup.page.html
Labels: design

#34 Profile Feature for Demo One
  libs/app/core/src/core.module.ts
  libs/app/core/src/core.routing.ts
  libs/app/profile/feature/.eslintrc.json
  libs/app/profile/feature/README.md
  libs/app/profile/feature/jest.config.ts
  libs/app/profile/feature/project.json
  libs/app/profile/feature/src/index.ts
  libs/app/profile/feature/src/profile.module.ts
  libs/app/profile/feature/src/profile.page.html
  libs/app/profile/feature/src/profile.page.scss
  libs/app/profile/feature/src/profile.page.spec.ts
  libs/app/profile/feature/src/profile.page.ts
  libs/app/profile/feature/src/profile.routing.ts
  libs/app/profile/feature/src/test-setup.ts
  libs/app/profile/feature/tsconfig.json
  libs/app/profile/feature/tsconfig.lib.json
  libs/app/profile/feature/tsconfig.spec.json
  tsconfig.base.json
Labels: enhancement

#39 Recommendation Feature for Demo One
  apps/app/src/main.ts
  apps/app/tailwind.config.js
  libs/app/core/src/core.module.ts
  libs/app/core/src/core.routing.ts
  libs/app/core/src/core.shell.html
  libs/app/core/src/nx-welcome.component.ts
  libs/app/core/src/tabbed-component/tabbed-component.html
  libs/app/core/src/tabbed-component/tabbed-component.scss
  libs/app/core/src/tabbed-component/tabbed-component.spec.ts
  libs/app/core/src/tabbed-component/tabbed-component.ts
  libs/app/recipe-recommendation/.eslintrc.json
  libs/app/recipe-recommendation/README.md
  libs/app/recipe-recommendation/jest.config.ts
  libs/app/recipe-recommendation/project.json
  libs/app/recipe-recommendation/src/app-recipe-recommendation.module.ts
  libs/app/recipe-recommendation/src/components/RecipeRecommendationPage/recipe-recommendation-page.html
  libs/app/recipe-recommendation/src/components/RecipeRecommendationPage/recipe-recommendation-page.scss
  libs/app/recipe-recommendation/src/components/RecipeRecommendationPage/recipe-recommendation-page.spec.ts
  libs/app/recipe-recommendation/src/components/RecipeRecommendationPage/recipe-recommendation-page.ts
  libs/app/recipe-recommendation/src/components/item-edit-step/item-edit-step.html
  libs/app/recipe-recommendation/src/components/item-edit-step/item-edit-step.scss
  libs/app/recipe-recommendation/src/components/item-edit-step/item-edit-step.spec.ts
  libs/app/recipe-recommendation/src/components/item-edit-step/item-edit-step.ts
  libs/app/recipe-recommendation/src/components/recipe-list-step/recipe-list-step.html
  libs/app/recipe-recommendation/src/components/recipe-list-step/recipe-list-step.scss
  libs/app/recipe-recommendation/src/components/recipe-list-step/recipe-list-step.spec.ts
  libs/app/recipe-recommendation/src/components/recipe-list-step/recipe-list-step.ts
  libs/app/recipe-recommendation/src/components/recipe-preferences-step/recipe-preferences-step.html
  libs/app/recipe-recommendation/src/components/recipe-preferences-step/recipe-preferences-step.scss
  libs/app/recipe-recommendation/src/components/recipe-preferences-step/recipe-preferences-step.spec.ts
  libs/app/recipe-recommendation/src/components/recipe-preferences-step/recipe-preferences-step.ts
  libs/app/recipe-recommendation/src/components/stepper-form/steper-form.spec.ts
  libs/app/recipe-recommendation/src/components/stepper-form/stepper-form.html
  libs/app/recipe-recommendation/src/components/stepper-form/stepper-form.scss
  libs/app/recipe-recommendation/src/components/stepper-form/stepper-form.ts
  libs/app/recipe-recommendation/src/data-access/api/recipe-recommendation-api.ts
  libs/app/recipe-recommendation/src/data-access/mock-data/ingredients.ts
  libs/app/recipe-recommendation/src/data-access/mock-data/recipes.ts
  libs/app/recipe-recommendation/src/data-access/store/state.ts
  libs/app/recipe-recommendation/src/index.ts
  libs/app/recipe-recommendation/src/recommendation.routing.ts
  libs/app/recipe-recommendation/src/test-setup.ts
  libs/app/recipe-recommendation/tsconfig.json
  libs/app/recipe-recommendation/tsconfig.lib.json
  libs/app/recipe-recommendation/tsconfig.spec.json
  package-lock.json
  package.json
  tsconfig.base.json
Labels: enhancement

#43 Auth Feature for Demo One
  apps/app/src/assets/Logo.png
  libs/app/core/src/core.module.ts
  libs/app/core/src/core.routing.ts
  libs/app/login/feature/.eslintrc.json
  libs/app/login/feature/README.md
  libs/app/login/feature/jest.config.ts
  libs/app/login/feature/project.json
  libs/app/login/feature/src/index.ts
  libs/app/login/feature/src/login.module.ts
  libs/app/login/feature/src/login.page.html
  libs/app/login/feature/src/login.page.scss
  libs/app/login/feature/src/login.page.spec.ts
  libs/app/login/feature/src/login.page.ts
  libs/app/login/feature/src/login.routing.ts
  libs/app/login/feature/src/test-setup.ts
  libs/app/login/feature/tsconfig.json
  libs/app/login/feature/tsconfig.lib.json
  libs/app/login/feature/tsconfig.spec.json
  libs/app/signup/feature/.eslintrc.json
  libs/app/signup/feature/README.md
  libs/app/signup/feature/jest.config.ts
  libs/app/signup/feature/package.json
  libs/app/signup/feature/project.json
  libs/app/signup/feature/src/index.ts
  libs/app/signup/feature/src/signup.module.ts
  libs/app/signup/feature/src/signup.page.html
  libs/app/signup/feature/src/signup.page.scss
  libs/app/signup/feature/src/signup.page.ts
  libs/app/signup/feature/src/signup.routing.ts
  libs/app/signup/feature/src/test-setup.ts
  libs/app/signup/feature/tsconfig.json
  libs/app/signup/feature/tsconfig.lib.json
  libs/app/signup/feature/tsconfig.spec.json
  package-lock.json
  tsconfig.base.json
Labels: documentation
