Repository COS301-SE-2023/FridgeToPlate, pull requests merged in 2023-10, with the labels that each got.

#373 fix: :bug: Fixed chart initialization bug
  libs/app/profile/data-access/src/profile.state.ts
Labels: bug, frontend

#370 369 edit reviews
  libs/app/recipe/data-access/src/recipe.state.ts
  libs/app/review/feature/src/review.component.ts
  libs/app/review/feature/src/review.html
  libs/app/review/feature/src/review.scss
Labels: bug, frontend

#375 367 bug sign up feedback
  libs/app/auth/data-access/src/auth.state.ts
  libs/app/login/feature/src/login.page.html
  libs/app/login/feature/src/login.page.ts
  libs/app/profile/data-access/src/profile.state.ts
  libs/app/signup/feature/src/signup.page.html
  libs/app/signup/feature/src/signup.page.ts
Labels: bug, frontend

#371 364 bug change profile information
  libs/app/auth/data-access/src/auth.state.ts
  libs/app/auth/utils/src/auth.actions.ts
  libs/app/profile/data-access/src/profile.api.ts
  libs/app/profile/data-access/src/profile.state.ts
  libs/app/profile/ui/src/edit-modal/edit-modal.component.html
  libs/app/profile/ui/src/edit-modal/edit-modal.component.spec.ts
  libs/app/profile/ui/src/edit-modal/edit-modal.component.ts
Labels: bug, frontend

#377 372 bug rating amount decimal places
  libs/app/create/feature/src/create.page.html
  libs/app/edit-recipe/feature/src/edit-recipe.page.html
  libs/app/recipe/ui/src/recipe-card/recipe-card.component.html
Labels: bug, enhancement, frontend

#376 365 bug dark mode
  libs/app/forgot/feature/src/forgot.page.html
  libs/app/forgot/ui/src/confirm-modal/confirm-modal.component.html
  libs/app/forgot/ui/src/verification-modal/verification-modal.component.html
  libs/app/help/feature/src/help.page.html
  libs/app/notifications/feature/src/notifications.page.html
  libs/app/notifications/feature/src/notifications.page.scss
  libs/app/profile/feature/src/profile.page.html
  libs/app/recommend/ui/src/dropdown-select/dropdown-select.component.html
  libs/app/recommend/ui/src/recipe-preferences-step/recipe-preferences-step.html
  libs/app/signup/feature/src/signup.page.html
  libs/app/unauthorised/feature/src/unauthorised.page.html
Labels: bug, frontend

#384 Update Help Page
  apps/app/src/assets/Adding to Meal Plan.png
  apps/app/src/assets/Adding to meal plan [Date selection].png
  apps/app/src/assets/Adding to meal plan [Meal type selection].png
  apps/app/src/assets/Create Page [Lower Half] - Completed.png
  apps/app/src/assets/Create Page [Lower Half].png
  apps/app/src/assets/Create Page [Upper half] - Completed.png
  apps/app/src/assets/Create Page [Upper half].png
  apps/app/src/assets/Edit Password Modal.png
  apps/app/src/assets/Featured Recipes.png
  apps/app/src/assets/Home Page Display.png
  apps/app/src/assets/Meal Plan Calender.png
  apps/app/src/assets/Meal Plan Calories.png
  apps/app/src/assets/Meal Plan Shopping List.png
  apps/app/src/assets/Mobile Create Page [Lower half] completed.png
  apps/app/src/assets/Mobile Create Page [Lower half].png
  apps/app/src/assets/Mobile Create Page [Upper half] completed.png
  apps/app/src/assets/Mobile Create Page [Upper half].png
  apps/app/src/assets/Mobile Home Page Display.png
  apps/app/src/assets/Mobile NavBar Image [Unselected].png
  apps/app/src/assets/Mobile Notification Page.png
  apps/app/src/assets/Mobile Profile Page [Edit Profile Modal].png
  apps/app/src/assets/Mobile Profile Page [Username and Edit Profile section].png
  apps/app/src/assets/Mobile Recipe Detail Page [Lower half].png
  apps/app/src/assets/Mobile Recipe Detail Page [Middle half].png
  apps/app/src/assets/Mobile Recipe Detail Page [Upper half].png
  apps/app/src/assets/Mobile Search Page.png
  apps/app/src/assets/Mobile Search [Chicken search].png
  apps/app/src/assets/Mobile Search history.png
  apps/app/src/assets/Mobile step 1 Recommend.png
  apps/app/src/assets/Mobile step 2 Recommend.png
  apps/app/src/assets/NavBar Image [Unselected].png
  apps/app/src/assets/NavBar Image.png
  apps/app/src/assets/Notifications Page.png
  apps/app/src/assets/Profile Page Full Display.png
  apps/app/src/assets/Profile Page [Edit Profile Modal].png
  apps/app/src/assets/Profile Page [Meal plan] - lower half.png
  apps/app/src/assets/Profile Page [Meal plan].png
  apps/app/src/assets/Profile Page [Saved Recipes].png
  apps/app/src/assets/Profile Page [Username and Edit Profile section].png
  apps/app/src/assets/Profile page [Created Recipes].png
  apps/app/src/assets/Recipe Card.png
  apps/app/src/assets/Recipe Detail Page [Lower half].png
  apps/app/src/assets/Recipe Detail Page [Upper half].png
  apps/app/src/assets/Recommend Display Page.png
  apps/app/src/assets/Search Page Display.png
  apps/app/src/assets/Search bar.png
  apps/app/src/assets/Search results [Chicken Search].png
  apps/app/src/assets/Settings Modal.png
  libs/app/help/feature/src/help.page.html
  libs/app/notifications/data-access/src/notifications.api.ts
Labels: documentation, enhancement

#385 382 tweak recipe page
  libs/app/recipe/feature/src/recipe.page.html
  libs/app/recipe/ui/src/recipe-card/recipe-card.component.ts
  libs/app/review/feature/src/review.component.ts
  libs/app/review/feature/src/review.html
  libs/app/review/feature/src/review.spec.ts
Labels: enhancement, frontend

#388 Update README.md
  README.md
Labels: documentation
