Repository COS301-SE-2023/FridgeToPlate, pull requests merged in 2023-09, with the labels that each got.

#272 251 uiux recipe 1
  libs/app/recipe/data-access/src/recipe.state.ts
  libs/app/recipe/feature/src/recipe.page.html
  libs/app/recipe/feature/src/recipe.page.spec.ts
  libs/app/recipe/feature/src/recipe.page.ts
  libs/app/review/feature/src/review.html
  libs/app/review/feature/src/review.scss
Labels: design, frontend

#270 243 recommend service refactor
  apps/api/src/main/java/com/fridgetoplate/controller/RecommendController.java
  apps/api/src/main/java/com/fridgetoplate/frontendmodels/RecipeFrontendModel.java
  apps/api/src/main/java/com/fridgetoplate/frontendmodels/RecipePreferencesFrontendModel.java
  apps/api/src/main/java/com/fridgetoplate/interfaces/Recipe.java
  apps/api/src/main/java/com/fridgetoplate/interfaces/RecipeDesc.java
  apps/api/src/main/java/com/fridgetoplate/model/Ingredient.java
  apps/api/src/main/java/com/fridgetoplate/model/IngredientModel.java
  apps/api/src/main/java/com/fridgetoplate/model/RecipeModel.java
  apps/api/src/main/java/com/fridgetoplate/model/RecommendModel.java
  apps/api/src/main/java/com/fridgetoplate/repository/ExploreRepository.java
  apps/api/src/main/java/com/fridgetoplate/repository/RecipeRepository.java
  apps/api/src/main/java/com/fridgetoplate/repository/RecommendRepository.java
  apps/api/src/main/java/com/fridgetoplate/service/ExternalApiService.java
  apps/api/src/main/java/com/fridgetoplate/service/RecipeService.java
  apps/api/src/main/java/com/fridgetoplate/service/RecommendService.java
  apps/api/src/main/java/com/fridgetoplate/utils/IngredientArrayConverter.java
  apps/api/src/main/java/com/fridgetoplate/utils/RecipeArrayConverter.java
  apps/api/src/main/java/com/fridgetoplate/utils/RecipePreferencesConverter.java
  apps/api/src/main/java/com/fridgetoplate/utils/ReviewArrayConverter.java
  apps/api/src/main/java/com/fridgetoplate/utils/SpoonacularRecipeConverter.java
  libs/app/create/feature/src/create.page.html
  libs/app/create/feature/src/create.page.spec.ts
  libs/app/create/feature/src/create.page.ts
  libs/app/edit-recipe/feature/src/edit-recipe.page.spec.ts
  libs/app/edit-recipe/feature/src/edit-recipe.page.ts
  libs/app/explore/feature/src/explore.page.spec.ts
  libs/app/models/api.response.ts
  libs/app/profile/data-access/src/profile.state.ts
  libs/app/recipe/feature/src/recipe.page.spec.ts
  libs/app/recipe/ui/src/recipe-card/recipe-card.component.spec.ts
  libs/app/recipe/utils/src/interfaces/recipe.interface.ts
  libs/app/recommend/utils/src/interfaces/recipe-preference.interface.ts
Labels: enhancement, backend

#275 Explore Service Refactor
  apps/api/src/main/java/com/fridgetoplate/api/ApiApplication.java
  apps/api/src/main/java/com/fridgetoplate/config/DynamoDBConfiguration.java
  apps/api/src/main/java/com/fridgetoplate/controller/ExploreController.java
  apps/api/src/main/java/com/fridgetoplate/interfaces/Explore.java
  apps/api/src/main/java/com/fridgetoplate/repository/ExploreRepository.java
  apps/api/src/main/java/com/fridgetoplate/repository/RecipeRepository.java
  apps/api/src/main/java/com/fridgetoplate/service/ExploreApiService.java
  apps/api/src/main/java/com/fridgetoplate/service/ExternalApiService.java
  apps/api/src/main/java/com/fridgetoplate/service/RecipeService.java
  apps/api/src/main/resources/application.properties
  apps/api/src/test/java/com/fridgetoplate/api/ApiApplicationTests.java
Labels: enhancement, backend

#269 248 uiux authentication
  apps/app/src/assets/App Logo.png
  apps/app/src/assets/Fridge Logo Transparent.png
  apps/app/src/assets/Fridge Transparent.png
  apps/app/src/assets/Logo Transparent.png
  apps/app/src/assets/New Logo.jpg
  libs/app/login/feature/src/login.page.html
  libs/app/login/feature/src/login.page.ts
  libs/app/signup/feature/src/signup.page.html
  libs/app/signup/feature/src/signup.page.ts
Labels: enhancement, frontend

#284 245 recipe service refactor 3
  apps/api/src/main/java/com/fridgetoplate/controller/RecipeController.java
  apps/api/src/main/java/com/fridgetoplate/repository/RecipeRepository.java
  apps/api/src/main/java/com/fridgetoplate/service/RecipeService.java
  libs/app/profile/feature/src/profile.page.html
  libs/app/profile/feature/src/profile.page.ts
Labels: enhancement, backend

#286 Implement Recipe Analytics
  apps/api/src/main/java/com/fridgetoplate/controller/RecipeController.java
  apps/api/src/main/java/com/fridgetoplate/interfaces/Recipe.java
  apps/api/src/main/java/com/fridgetoplate/repository/RecipeRepository.java
  apps/api/src/main/java/com/fridgetoplate/repository/ReviewRepository.java
  apps/api/src/main/java/com/fridgetoplate/service/RecipeService.java
  libs/app/profile/feature/src/profile.page.html
  libs/app/recipe/data-access/src/recipe.api.ts
  libs/app/recipe/data-access/src/recipe.state.ts
  libs/app/recipe/ui/src/recipe-card/recipe-card.component.html
  libs/app/recipe/ui/src/recipe-card/recipe-card.component.scss
  libs/app/recipe/ui/src/recipe-card/recipe-card.component.spec.ts
  libs/app/recipe/ui/src/recipe-card/recipe-card.component.ts
  libs/app/recipe/utils/src/recipe.actions.ts
Labels: enhancement, backend, database

#285 239 notification service refactor
  apps/api/src/main/java/com/fridgetoplate/controller/NotificationController.java
  apps/api/src/main/java/com/fridgetoplate/repository/ExploreRepository.java
  apps/api/src/main/java/com/fridgetoplate/repository/NotificationsRepository.java
  apps/api/src/main/java/com/fridgetoplate/service/NotificationService.java
  libs/app/create/feature/src/create.page.html
  libs/app/create/feature/src/create.page.spec.ts
  libs/app/create/feature/src/create.page.ts
  libs/app/notifications/data-access/src/index.ts
  libs/app/notifications/data-access/src/mock-data/notifications-test.json
  libs/app/notifications/data-access/src/notifications.api.ts
  libs/app/notifications/data-access/src/notifications.state.ts
  libs/app/notifications/feature/src/notifications.page.spec.ts
  libs/app/notifications/feature/src/notifications.page.ts
  libs/app/notifications/utils/src/index.ts
  libs/app/notifications/utils/src/notifications.actions.ts
  libs/app/splash/ui/src/splash.page.html
  libs/app/splash/ui/src/splash.page.ts
Labels: enhancement, frontend, backend

#291 Review Service Refactor
  apps/api/src/main/java/com/fridgetoplate/controller/ExploreController.java
  apps/api/src/main/java/com/fridgetoplate/controller/MealPlanController.java
  apps/api/src/main/java/com/fridgetoplate/controller/NotificationController.java
  apps/api/src/main/java/com/fridgetoplate/controller/PreferencesController.java
  apps/api/src/main/java/com/fridgetoplate/controller/RecipeController.java
  apps/api/src/main/java/com/fridgetoplate/controller/RecommendController.java
  apps/api/src/main/java/com/fridgetoplate/controller/ReviewController.java
  apps/api/src/main/java/com/fridgetoplate/model/Ingredient.java
  apps/api/src/main/java/com/fridgetoplate/model/IngredientModel.java
  apps/api/src/main/java/com/fridgetoplate/repository/RecipeRepository.java
  apps/api/src/main/java/com/fridgetoplate/repository/ReviewRepository.java
  apps/api/src/main/java/com/fridgetoplate/service/ExploreService.java
  apps/api/src/main/java/com/fridgetoplate/service/MealPlanService.java
  apps/api/src/main/java/com/fridgetoplate/service/NotificationService.java
  apps/api/src/main/java/com/fridgetoplate/service/RecipeService.java
  apps/api/src/main/java/com/fridgetoplate/service/RecommendService.java
  apps/api/src/main/java/com/fridgetoplate/service/ReviewService.java
Labels: documentation, backend

#279 252 uiux recommend
  libs/app/core/src/core.module.ts
  libs/app/explore/feature/src/explore.page.html
  libs/app/profile/feature/src/profile.module.ts
  libs/app/recommend/ui/src/dropdown-select/dropdown-select.component.css
  libs/app/recommend/ui/src/dropdown-select/dropdown-select.component.html
  libs/app/recommend/ui/src/dropdown-select/dropdown-select.component.spec.ts
  libs/app/recommend/ui/src/dropdown-select/dropdown-select.component.ts
  libs/app/recommend/ui/src/index.ts
  libs/app/recommend/ui/src/item-edit-step/item-edit-step.html
  libs/app/recommend/ui/src/item-edit-step/item-edit-step.scss
  libs/app/recommend/ui/src/item-edit-step/item-edit-step.ts
  libs/app/recommend/ui/src/recipe-list-step/recipe-list-step.html
  libs/app/recommend/ui/src/recipe-preferences-step/recipe-preferences-step.html
  libs/app/recommend/ui/src/recipe-preferences-step/recipe-preferences-step.spec.ts
  libs/app/recommend/ui/src/recipe-preferences-step/recipe-preferences-step.ts
  libs/app/recommend/ui/src/recommend.module.ts
  libs/app/recommend/ui/src/stepper-form/stepper-form.html
  libs/app/recommend/utils/src/index.ts
  libs/app/recommend/utils/src/keywordsList.ts
  libs/app/recommend/utils/src/units.ts
  package-lock.json
  package.json
Labels: bug, enhancement, frontend

#298 UI hot fix
  libs/app/create/feature/src/create.page.html
  libs/app/navigation/feature/src/navigation.component.html
  libs/app/recipe/feature/src/recipe.page.html
  libs/app/recipe/feature/src/recipe.page.ts
Labels: design, frontend

#293 Backend Hotfix
  apps/api/src/main/java/com/fridgetoplate/controller/ProfileController.java
  apps/api/src/main/java/com/fridgetoplate/controller/RecommendController.java
  apps/api/src/main/java/com/fridgetoplate/repository/RecipeRepository.java
  apps/api/src/main/java/com/fridgetoplate/service/ExternalApiService.java
  apps/api/src/main/java/com/fridgetoplate/service/RecipeService.java
  apps/api/src/main/java/com/fridgetoplate/service/RecommendService.java
  apps/api/src/main/java/com/fridgetoplate/utils/SpoonacularRecipeConverter.java
  libs/app/create/feature/src/create.page.html
  libs/app/create/feature/src/create.page.spec.ts
  libs/app/create/feature/src/create.page.ts
  libs/app/edit-recipe/feature/src/edit-recipe.page.html
  libs/app/edit-recipe/feature/src/edit-recipe.page.spec.ts
  libs/app/edit-recipe/feature/src/edit-recipe.page.ts
  libs/app/recipe/data-access/src/recipe.state.ts
  libs/app/recipe/feature/src/recipe.page.html
Labels: bug, backend

#302 257 bug error on recipe deletion
  apps/api/src/main/java/com/fridgetoplate/controller/RecipeController.java
  apps/api/src/main/java/com/fridgetoplate/model/RecipeDeleteResponseModel.java
  apps/api/src/main/java/com/fridgetoplate/service/RecipeService.java
  libs/app/recipe/data-access/src/recipe.api.ts
  libs/app/recipe/utils/src/interfaces/delete.recipe.response.ts
Labels: bug, documentation, frontend, backend

#294 230 unit conversions
  apps/app-e2e/cypress/downloads/downloads.html
  libs/app/create/feature/src/create.page.html
  libs/app/explore/data-access/src/explore.api.ts
  libs/app/explore/data-access/src/explore.mock.ts
  libs/app/recipe/data-access/src/mock-data/index.ts
  libs/app/recipe/data-access/src/mock-data/mock-recipe-data.ts
  libs/app/recipe/data-access/src/recipe.state.ts
  libs/app/recipe/feature/src/recipe.module.ts
  libs/app/recipe/feature/src/recipe.page.html
  libs/app/recipe/feature/src/recipe.page.spec.ts
  libs/app/recipe/feature/src/recipe.page.ts
  libs/app/recipe/ui/src/recipe.module.ts
  libs/app/recipe/utils/src/recipe.actions.ts
  libs/app/recommend/data-access/src/index.ts
  libs/app/recommend/data-access/src/ingredients.mock.ts
  libs/app/recommend/data-access/src/recipes.mock.ts
  libs/app/recommend/data-access/src/recommend.api.ts
Labels: enhancement, frontend

#304 301 uiux revised general application
  apps/app/src/styles.scss
  apps/app/tailwind.config.js
  libs/app/create/feature/src/create.page.html
  libs/app/home/feature/src/home.page.html
  libs/app/ingredient/ui/src/ingredient-card/ingredient-card.component.html
Labels: enhancement, frontend

#305 UI/UX: Revised Create and Edit Recipe
  libs/app/create/feature/src/create.page.html
  libs/app/create/feature/src/create.page.spec.ts
  libs/app/create/feature/src/create.page.ts
  libs/app/edit-recipe/feature/src/edit-recipe.page.html
  libs/app/edit-recipe/feature/src/edit-recipe.page.spec.ts
  libs/app/edit-recipe/feature/src/edit-recipe.page.ts
  libs/app/recipe/data-access/src/recipe.state.ts
Labels: enhancement, frontend

#311 288 add info toast 1
  libs/app/auth/data-access/src/auth.state.ts
  libs/app/core/src/core.module.ts
  libs/app/create/feature/src/create.page.html
  libs/app/create/feature/src/create.page.spec.ts
  libs/app/create/feature/src/create.page.ts
  libs/app/error/data-access/src/error.state.ts
  libs/app/error/utils/src/error.actions.ts
  libs/app/explore/data-access/src/explore.state.ts
  libs/app/forgot/ui/src/verification-modal/verification-modal.component.ts
  libs/app/home/data-access/src/home.state.ts
  libs/app/info/data-access/.eslintrc.json
  libs/app/info/data-access/README.md
  libs/app/info/data-access/jest.config.ts
  libs/app/info/data-access/project.json
  libs/app/info/data-access/src/index.ts
  libs/app/info/data-access/src/info.state.ts
  libs/app/info/data-access/src/test-setup.ts
  libs/app/info/data-access/tsconfig.json
  libs/app/info/data-access/tsconfig.lib.json
  libs/app/info/data-access/tsconfig.spec.json
  libs/app/info/utils/.eslintrc.json
  libs/app/info/utils/README.md
  libs/app/info/utils/jest.config.ts
  libs/app/info/utils/project.json
  libs/app/info/utils/src/index.ts
  libs/app/info/utils/src/info.actions.ts
  libs/app/info/utils/src/info.module.ts
  libs/app/info/utils/src/test-setup.ts
  libs/app/info/utils/tsconfig.json
  libs/app/info/utils/tsconfig.lib.json
  libs/app/info/utils/tsconfig.spec.json
  libs/app/notifications/data-access/src/notifications.state.ts
  libs/app/profile/data-access/src/profile.state.ts
  libs/app/profile/ui/src/password-modal/password-modal.component.html
  libs/app/profile/ui/src/password-modal/password-modal.component.spec.ts
  libs/app/profile/ui/src/password-modal/password-modal.component.ts
  libs/app/recipe/data-access/src/recipe.state.ts
  tsconfig.base.json
Labels: enhancement, frontend

#308 297 uiux revised explore
  libs/app/explore/feature/src/explore.module.ts
  libs/app/explore/feature/src/explore.page.html
  libs/app/explore/feature/src/explore.page.spec.ts
  libs/app/explore/feature/src/explore.page.ts
  libs/app/explore/ui/src/searching-modal/searching-modal.component.html
  libs/app/explore/ui/src/searching-modal/searching-modal.component.spec.ts
  libs/app/explore/ui/src/searching-modal/searching-modal.component.ts
  libs/app/recipe/ui/src/meal-plan-modal/meal-plan-modal.component.spec.ts
  libs/app/recommend/ui/src/dropdown-select/dropdown-select.component.spec.ts
  libs/app/recommend/ui/src/item-edit-step/item-edit-step.spec.ts
  libs/app/recommend/ui/src/recipe-list-step/recipe-list-step.spec.ts
  libs/app/recommend/ui/src/recipe-preferences-step/recipe-preferences-step.spec.ts
  libs/app/recommend/ui/src/stepper-form/steper-form.spec.ts
  package-lock.json
Labels: bug, enhancement, design, frontend

#307 237 create logo and splash screen
  libs/app/login/feature/src/login.page.html
  libs/app/signup/feature/src/signup.page.html
  libs/app/splash/ui/src/splash.page.html
Labels: frontend

#314 296 uiux revised create
  libs/app/create/feature/src/create.page.html
  libs/app/edit-recipe/feature/src/edit-recipe.page.html
Labels: bug, frontend

#315 240 push notifications
  apps/api/build.gradle
  apps/api/src/main/java/com/fridgetoplate/api/ApiApplication.java
  apps/api/src/main/java/com/fridgetoplate/config/WebSocketConfig.java
  apps/api/src/main/java/com/fridgetoplate/controller/MealPlanController.java
  apps/api/src/main/java/com/fridgetoplate/controller/NotificationController.java
  apps/api/src/main/java/com/fridgetoplate/controller/PushNotificationsController.java
  apps/api/src/main/java/com/fridgetoplate/controller/RecipeController.java
  apps/api/src/main/java/com/fridgetoplate/frontendmodels/NotificationsResponseModel.java
  apps/api/src/main/java/com/fridgetoplate/interfaces/Notification.java
  apps/api/src/main/java/com/fridgetoplate/model/NotificationModel.java
  apps/api/src/main/java/com/fridgetoplate/repository/MealPlanRepository.java
  apps/api/src/main/java/com/fridgetoplate/repository/NotificationsRepository.java
  apps/api/src/main/java/com/fridgetoplate/repository/ProfileRepository.java
  apps/api/src/main/java/com/fridgetoplate/service/MealPlanService.java
  apps/api/src/main/java/com/fridgetoplate/service/MessageService.java
  apps/api/src/main/java/com/fridgetoplate/service/NotificationService.java
  apps/api/src/main/java/com/fridgetoplate/service/ProfileModel.java
  apps/api/src/main/java/com/fridgetoplate/service/ProfileService.java
  apps/api/src/main/java/com/fridgetoplate/service/RecipeService.java
  apps/api/src/main/java/com/fridgetoplate/service/ReviewService.java
  apps/api/src/main/java/com/fridgetoplate/utils/NotificationsUtils.java
  apps/app/ngsw-config.json
  apps/app/project.json
  apps/app/src/main.ts
  libs/app/core/src/core.module.ts
  libs/app/core/src/core.shell.ts
  libs/app/core/src/services/web-socket.service.spec.ts
  libs/app/core/src/services/web-socket.service.ts
  libs/app/environments/utils/src/environment.ts
  libs/app/notifications/data-access/src/notifications.api.ts
  libs/app/notifications/data-access/src/notifications.state.ts
  libs/app/notifications/feature/src/notifications.page.html
  libs/app/notifications/feature/src/notifications.page.spec.ts
  libs/app/notifications/feature/src/notifications.page.ts
  libs/app/notifications/utils/src/interfaces/notifications.interface.ts
  libs/app/recommend/ui/src/recommend.module.ts
  package-lock.json
  package.json
Labels: enhancement, frontend, backend

#303 295 uiux revised profile
  .github/workflows/cd-dev.yml
  .github/workflows/ci-dev.yml
  .github/workflows/ci-prod.yml
  apps/api/src/main/java/com/fridgetoplate/controller/ExploreController.java
  apps/api/src/main/java/com/fridgetoplate/service/ExploreService.java
  apps/api/src/main/java/com/fridgetoplate/service/RecipeService.java
  apps/app-e2e/src/e2e/app.cy.ts
  apps/app/jest.config.ts
  libs/app/auth/data-access/src/auth.state.ts
  libs/app/home/data-access/src/home.state.ts
  libs/app/meal-plan/data-access/src/index.ts
  libs/app/meal-plan/data-access/src/meal-plan.state.ts
  libs/app/meal-plan/utils/src/index.ts
  libs/app/meal-plan/utils/src/meal-plan.actions.ts
  libs/app/profile/data-access/src/profile.module.ts
  libs/app/profile/data-access/src/profile.state.ts
  libs/app/profile/feature/jest.config.ts
  libs/app/profile/feature/src/profile.module.ts
  libs/app/profile/feature/src/profile.page.html
  libs/app/profile/feature/src/profile.page.spec.ts
  libs/app/profile/feature/src/profile.page.ts
  libs/app/profile/utils/src/profile.actions.ts
  libs/app/recipe/data-access/src/recipe.state.ts
  libs/app/recipe/feature/src/lib/recipe-error/recipe-error.component.css
  libs/app/recipe/feature/src/lib/recipe-error/recipe-error.component.html
  libs/app/recipe/feature/src/lib/recipe-error/recipe-error.component.spec.ts
  libs/app/recipe/feature/src/lib/recipe-error/recipe-error.component.ts
  libs/app/recipe/feature/src/recipe.page.html
  libs/app/recipe/feature/src/recipe.page.spec.ts
  libs/app/recipe/feature/src/recipe.page.ts
  libs/app/recipe/feature/src/recipe.routing.ts
  libs/app/recipe/ui/src/meal-plan-modal/meal-plan-modal.component.html
  libs/app/recipe/ui/src/meal-plan-modal/meal-plan-modal.component.spec.ts
  libs/app/recipe/ui/src/meal-plan-modal/meal-plan-modal.component.ts
  libs/app/recipe/ui/src/recipe-card/recipe-card.component.spec.ts
  libs/app/recipe/ui/src/recipe-card/recipe-card.component.ts
  libs/app/recipe/utils/src/recipe.actions.ts
  libs/app/recommend/data-access/src/recommend.state.ts
  libs/app/recommend/feature/jest.config.ts
  libs/app/recommend/feature/src/recommend.page.spec.ts
  libs/app/recommend/feature/src/recommend.page.ts
  libs/app/recommend/ui/jest.config.ts
  libs/app/recommend/ui/src/barcode-modal/barcode-modal.component.html
  libs/app/recommend/ui/src/barcode-modal/barcode-modal.component.ts
  libs/app/recommend/ui/src/item-edit-step/item-edit-step.spec.ts
  libs/app/recommend/utils/src/functions/recommendUtilFunctions.ts
  libs/app/review/feature/src/review.component.ts
  libs/app/review/feature/src/review.html
  package-lock.json
  package.json
Labels: frontend

#312 300 uiux revised recipe
  libs/app/recipe/feature/src/recipe.page.spec.ts
  libs/app/recipe/feature/src/recipe.page.ts
  libs/app/recipe/ui/src/recipe-card/recipe-card.component.spec.ts
Labels: enhancement, frontend

#316 300 uiux revised recipe
  libs/app/recipe/feature/src/recipe.page.spec.ts
  libs/app/recipe/ui/src/recipe-card/recipe-card.component.spec.ts
Labels: bug, frontend

#328 318 bug no skeleton loaders on home page
  libs/app/explore/feature/src/explore.page.html
  libs/app/home/data-access/src/home.state.ts
  libs/app/home/feature/src/home.page.html
  libs/app/home/feature/src/home.page.ts
  libs/app/home/utils/src/home.actions.ts
  libs/app/recipe/ui/src/custom-skeleton-loader/custom-skeleton-loader.component.css
  libs/app/recipe/ui/src/custom-skeleton-loader/custom-skeleton-loader.component.html
  libs/app/recipe/ui/src/custom-skeleton-loader/custom-skeleton-loader.component.spec.ts
  libs/app/recipe/ui/src/custom-skeleton-loader/custom-skeleton-loader.component.ts
  libs/app/recipe/ui/src/recipe.module.ts
  libs/app/recommend/ui/src/recipe-list-step/recipe-list-step.html
Labels: bug, enhancement, frontend

#320 309 bug recommend page recipes showing from previous call
  apps/api/src/main/java/com/fridgetoplate/controller/RecipeController.java
  apps/api/src/main/java/com/fridgetoplate/model/NotificationModel.java
  apps/api/src/main/java/com/fridgetoplate/repository/NotificationsRepository.java
  apps/api/src/main/java/com/fridgetoplate/repository/RecipeRepository.java
  apps/api/src/main/java/com/fridgetoplate/service/NotificationService.java
  apps/api/src/main/java/com/fridgetoplate/service/RecipeService.java
  apps/api/src/main/java/com/fridgetoplate/service/RecommendService.java
  apps/api/src/main/java/com/fridgetoplate/service/ReviewService.java
  apps/api/src/main/java/com/fridgetoplate/utils/NotificationsUtils.java
  apps/api/src/main/java/com/fridgetoplate/utils/SpoonacularRecipeConverter.java
  libs/app/notifications/data-access/src/notifications.state.ts
  libs/app/profile/data-access/src/profile.state.ts
  libs/app/recipe/data-access/src/recipe.api.ts
  libs/app/recipe/data-access/src/recipe.state.ts
  libs/app/recipe/feature/src/recipe.page.html
  libs/app/recipe/feature/src/recipe.page.spec.ts
  libs/app/recipe/feature/src/recipe.page.ts
  libs/app/recipe/ui/src/meal-plan-modal/meal-plan-modal.component.html
  libs/app/recipe/ui/src/recipe-card/recipe-card.component.spec.ts
  libs/app/recipe/ui/src/recipe-card/recipe-card.component.ts
  libs/app/recipe/utils/src/recipe.actions.ts
  libs/app/recommend/data-access/src/recommend.state.ts
  libs/app/recommend/ui/src/barcode-modal/barcode-modal.component.html
  libs/app/recommend/ui/src/item-edit-step/item-edit-step.html
  libs/app/recommend/ui/src/item-edit-step/item-edit-step.ts
  libs/app/recommend/ui/src/recipe-list-step/recipe-list-step.html
  libs/app/recommend/ui/src/stepper-form/stepper-form.html
Labels: bug, frontend

#331 317 bug search page not showing results
  apps/api/src/main/java/com/fridgetoplate/service/NotificationService.java
  libs/app/core/src/core.module.ts
  libs/app/explore/data-access/src/explore.module.ts
  libs/app/explore/data-access/src/explore.state.ts
  libs/app/explore/feature/src/explore.page.html
  libs/app/explore/feature/src/explore.page.ts
  libs/app/login/feature/src/login.page.ts
  libs/app/recipe/ui/src/custom-skeleton-loader/custom-skeleton-loader.component.html
  libs/app/signup/feature/src/signup.page.ts
Labels: bug

#338 334 top navbar covering content on signup and login
  libs/app/login/feature/src/login.page.html
  libs/app/notifications/feature/src/notifications.page.html
  libs/app/signup/feature/src/signup.page.html
Labels: bug, frontend

#333 Meal Plan Shopping List
  libs/app/profile/data-access/src/profile.state.ts
  libs/app/profile/ui/src/shopping-list-modal/shoppinglist.component.html
Labels: bug, frontend

#337 Hotfix/v1.0.0-beta
  apps/api/src/main/java/com/fridgetoplate/controller/RecipeController.java
  apps/api/src/main/java/com/fridgetoplate/model/NotificationModel.java
  apps/api/src/main/java/com/fridgetoplate/repository/NotificationsRepository.java
  apps/api/src/main/java/com/fridgetoplate/repository/RecipeRepository.java
  apps/api/src/main/java/com/fridgetoplate/service/NotificationService.java
  apps/api/src/main/java/com/fridgetoplate/service/RecipeService.java
  apps/api/src/main/java/com/fridgetoplate/service/RecommendService.java
  apps/api/src/main/java/com/fridgetoplate/service/ReviewService.java
  apps/api/src/main/java/com/fridgetoplate/utils/NotificationsUtils.java
  apps/api/src/main/java/com/fridgetoplate/utils/SpoonacularRecipeConverter.java
  libs/app/core/src/core.module.ts
  libs/app/explore/data-access/src/explore.module.ts
  libs/app/explore/data-access/src/explore.state.ts
  libs/app/explore/feature/src/explore.page.html
  libs/app/explore/feature/src/explore.page.ts
  libs/app/home/data-access/src/home.state.ts
  libs/app/home/feature/src/home.page.html
  libs/app/home/feature/src/home.page.ts
  libs/app/home/utils/src/home.actions.ts
  libs/app/login/feature/src/login.page.html
  libs/app/login/feature/src/login.page.ts
  libs/app/notifications/data-access/src/notifications.state.ts
  libs/app/notifications/feature/src/notifications.page.html
  libs/app/profile/data-access/src/profile.state.ts
  libs/app/profile/ui/src/shopping-list-modal/shoppinglist.component.html
  libs/app/recipe/data-access/src/recipe.api.ts
  libs/app/recipe/data-access/src/recipe.state.ts
  libs/app/recipe/feature/src/recipe.page.html
  libs/app/recipe/feature/src/recipe.page.spec.ts
  libs/app/recipe/feature/src/recipe.page.ts
  libs/app/recipe/ui/src/custom-skeleton-loader/custom-skeleton-loader.component.css
  libs/app/recipe/ui/src/custom-skeleton-loader/custom-skeleton-loader.component.html
  libs/app/recipe/ui/src/custom-skeleton-loader/custom-skeleton-loader.component.spec.ts
  libs/app/recipe/ui/src/custom-skeleton-loader/custom-skeleton-loader.component.ts
  libs/app/recipe/ui/src/meal-plan-modal/meal-plan-modal.component.html
  libs/app/recipe/ui/src/recipe-card/recipe-card.component.spec.ts
  libs/app/recipe/ui/src/recipe-card/recipe-card.component.ts
  libs/app/recipe/ui/src/recipe.module.ts
  libs/app/recipe/utils/src/recipe.actions.ts
  libs/app/recommend/data-access/src/recommend.state.ts
  libs/app/recommend/ui/src/barcode-modal/barcode-modal.component.html
  libs/app/recommend/ui/src/item-edit-step/item-edit-step.html
  libs/app/recommend/ui/src/item-edit-step/item-edit-step.ts
  libs/app/recommend/ui/src/recipe-list-step/recipe-list-step.html
  libs/app/recommend/ui/src/stepper-form/stepper-form.html
  libs/app/signup/feature/src/signup.page.html
  libs/app/signup/feature/src/signup.page.ts
Labels: bug, enhancement, frontend, backend

#340 325 profile add user feedback on empty saved and created recipes
  libs/app/profile/feature/src/profile.page.html
Labels: bug, frontend

#342 336 notifications covering their associated images
  libs/app/notifications/feature/src/notifications.page.html
  libs/app/review/feature/src/review.component.ts
  libs/app/review/feature/src/review.spec.ts
Labels: bug, frontend

#343 330 bug recipe page UI
  libs/app/recipe/feature/src/recipe.page.html
Labels: bug

#329 feat(none): :bug: Changed Search observable to emit on key 'Enter' in…
  libs/app/explore/feature/src/explore.page.html
  libs/app/explore/feature/src/explore.page.ts
  libs/app/explore/ui/src/searching-modal/searching-modal.component.html
  libs/app/explore/ui/src/searching-modal/searching-modal.component.spec.ts
  libs/app/explore/ui/src/searching-modal/searching-modal.component.ts
Labels: bug, enhancement

#354 344 auto meal plan chart refresh
  libs/app/meal-plan/data-access/src/meal-plan.state.ts
  libs/app/profile/data-access/src/profile.state.ts
  libs/app/profile/feature/src/profile.page.spec.ts
  libs/app/profile/feature/src/profile.page.ts
  libs/app/review/feature/src/review.html
Labels: bug, frontend

#341 326 uiux aesthetic updates
  apps/api/src/main/java/com/fridgetoplate/repository/RecipeRepository.java
  apps/api/src/main/java/com/fridgetoplate/service/ExploreService.java
  apps/api/src/main/java/com/fridgetoplate/service/RecipeService.java
  apps/app/tailwind.config.js
  libs/app/create/feature/src/create.page.html
  libs/app/create/feature/src/create.page.spec.ts
  libs/app/create/feature/src/create.page.ts
  libs/app/edit-recipe/feature/src/edit-recipe.page.html
  libs/app/edit-recipe/feature/src/edit-recipe.page.spec.ts
  libs/app/edit-recipe/feature/src/edit-recipe.page.ts
  libs/app/explore/feature/src/explore.page.html
  libs/app/explore/feature/src/explore.page.ts
  libs/app/home/feature/src/home.page.html
  libs/app/home/feature/src/home.page.spec.ts
  libs/app/home/feature/src/home.page.ts
  libs/app/navigation/feature/src/navigation.component.html
  libs/app/notifications/feature/src/notifications.page.html
  libs/app/notifications/ui/src/tabbed/tabbed.component.html
  libs/app/profile/feature/src/profile.page.html
  libs/app/profile/ui/src/settings-modal/settings-modal.component.html
  libs/app/recipe/feature/src/recipe.page.ts
  libs/app/recipe/ui/src/recipe-card/recipe-card.component.html
  libs/app/recommend/ui/src/item-edit-step/item-edit-step.html
  libs/app/recommend/ui/src/item-edit-step/item-edit-step.spec.ts
  libs/app/recommend/ui/src/item-edit-step/item-edit-step.ts
  libs/app/recommend/ui/src/recipe-preferences-step/recipe-preferences-step.html
  libs/app/recommend/ui/src/recommend.module.ts
  libs/app/recommend/ui/src/stepper-form/stepper-form.html
  libs/app/recommend/utils/src/units.ts
  libs/app/review/feature/src/review.component.ts
Labels: enhancement, frontend

#355 Recommend and Notification Preferences UI fix
  apps/api/src/main/java/com/fridgetoplate/repository/ExploreRepository.java
  apps/api/src/main/java/com/fridgetoplate/repository/RecipeRepository.java
  apps/api/src/main/java/com/fridgetoplate/service/ExternalApiService.java
  apps/api/src/main/java/com/fridgetoplate/service/NotificationService.java
  apps/api/src/main/java/com/fridgetoplate/service/RecipeService.java
  libs/app/auth/data-access/src/auth.state.ts
  libs/app/core/src/core.module.ts
  libs/app/create/feature/src/create.page.html
  libs/app/ingredient/ui/src/ingredient-card/ingredient-card.component.html
  libs/app/preferences/data-access/src/preferences.state.ts
  libs/app/preferences/utils/src/preferences.actions.ts
  libs/app/profile/ui/src/settings-modal/settings-modal.component.html
  libs/app/profile/ui/src/settings-modal/settings-modal.component.spec.ts
  libs/app/profile/ui/src/settings-modal/settings-modal.component.ts
  libs/app/recipe/feature/src/recipe.page.html
  libs/app/recipe/feature/src/recipe.page.ts
  libs/app/recipe/ui/src/recipe-card/recipe-card.component.html
  libs/app/recommend/ui/src/barcode-modal/barcode-modal.component.spec.ts
  libs/app/recommend/ui/src/barcode-modal/barcode-modal.component.ts
  libs/app/recommend/ui/src/item-edit-step/item-edit-step.html
  libs/app/recommend/ui/src/item-edit-step/item-edit-step.spec.ts
  libs/app/recommend/ui/src/item-edit-step/item-edit-step.ts
Labels: bug, enhancement, frontend

#356 351 update all error messages
  libs/app/auth/data-access/src/auth.state.ts
  libs/app/create/feature/src/create.page.spec.ts
  libs/app/create/feature/src/create.page.ts
  libs/app/edit-recipe/data-access/src/edit-recipe.state.ts
  libs/app/preferences/data-access/src/preferences.api.ts
  libs/app/preferences/data-access/src/preferences.state.ts
  libs/app/profile/data-access/src/profile.api.ts
  libs/app/profile/data-access/src/profile.state.ts
  libs/app/recipe/data-access/src/recipe.state.ts
  libs/app/recommend/data-access/src/recommend.state.ts
  libs/app/review/feature/src/review.component.ts
  libs/app/review/feature/src/review.spec.ts
Labels: bug, frontend

#359 test(none): Added PWA readiness and changed favicon
  apps/app/src/assets/android-chrome-192x192.png
  apps/app/src/assets/android-chrome-512x512.png
  apps/app/src/assets/app_logo.png
  apps/app/src/assets/apple-touch-icon.png
  apps/app/src/assets/favicon-16x16.png
  apps/app/src/assets/favicon-32x32.png
  apps/app/src/assets/mainifest.webmanifest
  apps/app/src/favicon.ico
  apps/app/src/index.html
  package-lock.json
  package.json
Labels: enhancement, frontend

#350 345 add change profile pic
  libs/app/profile/ui/src/edit-modal/edit-modal.component.html
  libs/app/profile/ui/src/edit-modal/edit-modal.component.spec.ts
  libs/app/profile/ui/src/edit-modal/edit-modal.component.ts
  libs/app/profile/ui/src/profile.module.ts
Labels: enhancement

#360 style: :lipstick: Added padding to explore page
  libs/app/explore/feature/src/explore.page.html
Labels: design, frontend

#357 352 dark mode setting
  apps/app/src/styles.scss
  apps/app/tailwind.config.js
  libs/app/create/feature/src/create.page.html
  libs/app/edit-recipe/feature/src/edit-recipe.page.html
  libs/app/explore/feature/src/explore.page.html
  libs/app/explore/ui/src/results-modal/results-modal.component.html
  libs/app/home/feature/src/home.page.html
  libs/app/login/feature/src/login.page.html
  libs/app/navigation/feature/src/navigation.component.html
  libs/app/navigation/feature/src/navigation.component.scss
  libs/app/navigation/feature/src/navigation.component.ts
  libs/app/notifications/feature/src/notifications.page.html
  libs/app/notifications/ui/src/tabbed/tabbed.component.html
  libs/app/preferences/data-access/src/preferences.state.ts
  libs/app/profile/feature/src/profile.page.html
  libs/app/profile/ui/src/edit-modal/edit-modal.component.html
  libs/app/profile/ui/src/password-modal/password-modal.component.html
  libs/app/profile/ui/src/shopping-list-modal/shoppinglist.component.html
  libs/app/recipe/feature/src/recipe.page.html
  libs/app/recipe/ui/src/meal-plan-modal/meal-plan-modal.component.html
  libs/app/recommend/feature/src/recommend.page.html
  libs/app/recommend/ui/src/barcode-modal/barcode-modal.component.html
  libs/app/recommend/ui/src/dropdown-select/dropdown-select.component.html
  libs/app/recommend/ui/src/item-edit-step/item-edit-step.html
  libs/app/recommend/ui/src/recipe-list-step/recipe-list-step.html
  libs/app/recommend/ui/src/recipe-preferences-step/recipe-preferences-step.html
  libs/app/recommend/ui/src/stepper-form/stepper-form.html
  libs/app/review/feature/src/review.html
  libs/app/signup/feature/src/signup.page.html
Labels: enhancement, design, frontend

#361 346 application help menu
  apps/api/src/main/java/com/fridgetoplate/service/RecommendService.java
  libs/app/auth/data-access/src/auth.state.ts
  libs/app/core/src/core.routing.ts
  libs/app/explore/feature/src/explore.page.html
  libs/app/explore/feature/src/explore.page.ts
  libs/app/help/feature/.eslintrc.json
  libs/app/help/feature/README.md
  libs/app/help/feature/jest.config.ts
  libs/app/help/feature/project.json
  libs/app/help/feature/src/help.module.ts
  libs/app/help/feature/src/help.page.html
  libs/app/help/feature/src/help.page.scss
  libs/app/help/feature/src/help.page.spec.ts
  libs/app/help/feature/src/help.page.ts
  libs/app/help/feature/src/help.routing.ts
  libs/app/help/feature/src/index.ts
  libs/app/help/feature/src/test-setup.ts
  libs/app/help/feature/tsconfig.json
  libs/app/help/feature/tsconfig.lib.json
  libs/app/help/feature/tsconfig.spec.json
  libs/app/profile/ui/src/settings-modal/settings-modal.component.html
  libs/app/profile/ui/src/settings-modal/settings-modal.component.ts
  libs/app/recommend/data-access/src/recommend.state.ts
  libs/app/recommend/ui/src/item-edit-step/item-edit-step.html
  libs/app/recommend/utils/src/recommend.actions.ts
  tsconfig.base.json
Labels: enhancement, frontend
