Repository COS301-SE-2023/FridgeToPlate, pull requests merged in 2023-06, with the labels that each got.

#45 Update README.md
  README.md
Labels: documentation

#62 Profile Responsivness
  libs/app/ingredient/ui/.eslintrc.json
  libs/app/ingredient/ui/README.md
  libs/app/ingredient/ui/jest.config.ts
  libs/app/ingredient/ui/project.json
  libs/app/ingredient/ui/src/index.ts
  libs/app/ingredient/ui/src/ingredient-card/ingredient-card.component.html
  libs/app/ingredient/ui/src/ingredient-card/ingredient-card.component.scss
  libs/app/ingredient/ui/src/ingredient-card/ingredient-card.component.spec.ts
  libs/app/ingredient/ui/src/ingredient-card/ingredient-card.component.ts
  libs/app/ingredient/ui/src/ingredient.module.ts
  libs/app/ingredient/ui/src/test-setup.ts
  libs/app/ingredient/ui/tsconfig.json
  libs/app/ingredient/ui/tsconfig.lib.json
  libs/app/ingredient/ui/tsconfig.spec.json
  libs/app/profile/feature/src/profile.module.ts
  libs/app/profile/feature/src/profile.page.html
  libs/app/recipe/ui/.eslintrc.json
  libs/app/recipe/ui/README.md
  libs/app/recipe/ui/jest.config.ts
  libs/app/recipe/ui/project.json
  libs/app/recipe/ui/src/index.ts
  libs/app/recipe/ui/src/recipe-card/recipe-card.component.html
  libs/app/recipe/ui/src/recipe-card/recipe-card.component.scss
  libs/app/recipe/ui/src/recipe-card/recipe-card.component.spec.ts
  libs/app/recipe/ui/src/recipe-card/recipe-card.component.ts
  libs/app/recipe/ui/src/recipe.module.ts
  libs/app/recipe/ui/src/test-setup.ts
  libs/app/recipe/ui/tsconfig.json
  libs/app/recipe/ui/tsconfig.lib.json
  libs/app/recipe/ui/tsconfig.spec.json
  tsconfig.base.json
Labels: enhancement, design, frontend

#69 Responsive Create Page
  apps/app/tailwind.config.js
  libs/app/create/feature/src/create.page.html
Labels: enhancement, design, frontend

#73 Create Responsive Design (Updated)
  libs/app/create/feature/src/create.page.html
Labels: enhancement, design, frontend

#74 Setup API CD Workflow
  .github/workflows/cd-dev.yml
  .github/workflows/cd-prod.yml
  apps/api/build.gradle
  apps/api/src/main/resources/application.properties
Labels: dev-ops

#87 Signup and Login Responsive Design
  libs/app/login/feature/src/login.module.ts
  libs/app/login/feature/src/login.page.html
  libs/app/login/feature/src/login.page.scss
  libs/app/login/feature/src/login.page.ts
  libs/app/signup/feature/src/signup.module.ts
  libs/app/signup/feature/src/signup.page.html
  libs/app/signup/feature/src/signup.page.ts
Labels: enhancement, design, frontend

#88 💚 (workflows) Fixed Zipping Error
  .github/workflows/cd-dev.yml
  .github/workflows/cd-prod.yml
Labels: bug, dev-ops

#92 Workspace CI and Coverage
  .github/workflows/ci-dev.yml
  .github/workflows/ci-prod.yml
  package.json
  tools/coverageMerger.js
Labels: dev-ops

#93 Feat/navigation
  .gitignore
  libs/app/create/feature/src/create.module.ts
  libs/app/create/feature/src/create.page.html
  libs/app/create/feature/src/create.page.ts
  libs/app/navigation/feature/.eslintrc.json
  libs/app/navigation/feature/README.md
  libs/app/navigation/feature/jest.config.ts
  libs/app/navigation/feature/package.json
  libs/app/navigation/feature/project.json
  libs/app/navigation/feature/src/app-navigation-feature.spec.ts
  libs/app/navigation/feature/src/app-navigation-feature.ts
  libs/app/navigation/feature/src/index.ts
  libs/app/navigation/feature/src/navigation.component.html
  libs/app/navigation/feature/src/navigation.component.module.ts
  libs/app/navigation/feature/src/navigation.component.scss
  libs/app/navigation/feature/src/navigation.component.ts
  libs/app/navigation/feature/tsconfig.json
  libs/app/navigation/feature/tsconfig.lib.json
  libs/app/navigation/feature/tsconfig.spec.json
  libs/app/profile/feature/src/profile.module.ts
  libs/app/profile/feature/src/profile.page.html
  libs/app/profile/feature/src/profile.page.ts
  libs/app/recipe/feature/src/recipe.module.ts
  libs/app/recipe/feature/src/recipe.page.html
  libs/app/recipe/feature/src/recipe.page.ts
  libs/app/recipe/ui/src/recipe-card/recipe-card.component.html
  libs/app/recommend/feature/src/recommend.module.ts
  libs/app/recommend/feature/src/recommend.page.html
  libs/app/recommend/feature/src/recommend.page.ts
  libs/app/services/auth.guard.ts
  libs/app/services/auth.service.spec.ts
  libs/app/services/auth.service.ts
  package-lock.json
  package.json
  tsconfig.base.json
Labels: enhancement, frontend

#98 48 setup database
  .github/workflows/cd-dev.yml
  .github/workflows/cd-prod.yml
  .github/workflows/ci-dev.yml
  .github/workflows/ci-prod.yml
  apps/api/build.gradle
  apps/api/src/main/java/com/fridgetoplate/api/ApiApplication.java
  apps/api/src/main/java/com/fridgetoplate/api/HelloController.java
  apps/api/src/main/java/com/fridgetoplate/api/IngredientController.java
  apps/api/src/main/java/com/fridgetoplate/api/PreferenceController.java
  apps/api/src/main/java/com/fridgetoplate/api/ProfileController.java
  apps/api/src/main/java/com/fridgetoplate/api/RecipeController.java
  apps/api/src/main/java/com/fridgetoplate/config/DynamoDBConfiguration.java
  apps/api/src/main/java/com/fridgetoplate/model/Ingredient.java
  apps/api/src/main/java/com/fridgetoplate/model/Preference.java
  apps/api/src/main/java/com/fridgetoplate/model/Profile.java
  apps/api/src/main/java/com/fridgetoplate/model/Recipe.java
  apps/api/src/main/java/com/fridgetoplate/repository/IngredientRepository.java
  apps/api/src/main/java/com/fridgetoplate/repository/PreferenceRepository.java
  apps/api/src/main/java/com/fridgetoplate/repository/ProfileRepository.java
  apps/api/src/main/java/com/fridgetoplate/repository/RecipeRepository.java
  apps/api/src/main/java/com/fridgetoplate/utils/IngredientArrayConverter.java
  apps/api/src/main/java/com/fridgetoplate/utils/RecipeArrayConverter.java
  apps/api/src/main/java/com/fridgetoplate/utils/StringArrayConverter.java
  apps/api/src/main/resources/application.properties
  libs/app/recipe/utils/src/interfaces/recipe.interface.ts
  tsconfig.base.json
Labels: enhancement, backend, database

#70 Update README.md
  README.md
Labels: documentation

#106 Feat/profile
  apps/api/src/main/java/com/fridgetoplate/api/ProfileController.java
  apps/api/src/main/java/com/fridgetoplate/model/Profile.java
  apps/api/src/main/java/com/fridgetoplate/repository/ProfileRepository.java
  libs/app/profile/data-access/src/profile.api.ts
  libs/app/profile/feature/src/profile.page.html
  libs/app/profile/feature/src/profile.page.spec.ts
  libs/app/profile/feature/src/profile.page.ts
  libs/app/profile/ui/src/edit-modal/edit-modal.component.html
  libs/app/profile/ui/src/edit-modal/edit-modal.component.spec.ts
  libs/app/profile/ui/src/edit-modal/edit-modal.component.ts
Labels: enhancement, backend, database

#104 Feat/create
  apps/api/src/main/java/com/fridgetoplate/api/IngredientController.java
  apps/api/src/main/java/com/fridgetoplate/api/PreferenceController.java
  apps/api/src/main/java/com/fridgetoplate/api/ProfileController.java
  apps/api/src/main/java/com/fridgetoplate/api/RecipeController.java
  apps/api/src/main/java/com/fridgetoplate/model/Profile.java
  apps/api/src/main/java/com/fridgetoplate/model/Recipe.java
  apps/api/src/main/java/com/fridgetoplate/model/RecipeStep.java
  apps/api/src/main/java/com/fridgetoplate/repository/IngredientRepository.java
  apps/api/src/main/java/com/fridgetoplate/utils/RecipeStepArrayConverter.java
  apps/api/src/main/resources/application.properties
  libs/app/create/data-access/.eslintrc.json
  libs/app/create/data-access/README.md
  libs/app/create/data-access/jest.config.ts
  libs/app/create/data-access/project.json
  libs/app/create/data-access/src/api/create.api.ts
  libs/app/create/data-access/src/create.module.ts
  libs/app/create/data-access/src/index.ts
  libs/app/create/data-access/src/test-setup.ts
  libs/app/create/data-access/tsconfig.json
  libs/app/create/data-access/tsconfig.lib.json
  libs/app/create/data-access/tsconfig.spec.json
  libs/app/create/feature/src/create.module.ts
  libs/app/create/feature/src/create.page.html
  libs/app/create/feature/src/create.page.spec.ts
  libs/app/create/feature/src/create.page.ts
  libs/app/ingredient/ui/src/ingredient-card/ingredient-card.component.spec.ts
  libs/app/ingredient/utils/src/interfaces/ingredient.interface.ts
  libs/app/profile/feature/src/profile.page.ts
  libs/app/recipe/data-access/src/mock-data/mock-recipe-data.ts
  libs/app/recipe/feature/src/recipe.page.html
  libs/app/recipe/ui/src/recipe-card/recipe-card.component.spec.ts
  libs/app/recipe/utils/src/interfaces/recipe.interface.ts
  tsconfig.base.json
Labels: enhancement, frontend, backend, database

#105 Feat/recommend
  apps/api/src/main/java/com/fridgetoplate/api/ProfileController.java
  apps/api/src/main/java/com/fridgetoplate/api/RecommendController.java
  libs/app/core/src/core.module.ts
  libs/app/ingredient/ui/src/ingredient-card/ingredient-card.component.spec.ts
  libs/app/recipe/feature/src/recipe.module.ts
  libs/app/recipe/ui/src/recipe-card/recipe-card.component.spec.ts
  libs/app/recommend/data-access/src/ingredients.mock.ts
  libs/app/recommend/data-access/src/recipes.mock.ts
  libs/app/recommend/data-access/src/recommend.api.ts
  libs/app/recommend/data-access/src/recommend.module.ts
  libs/app/recommend/data-access/src/store.state.ts
  libs/app/recommend/feature/src/recommend.module.ts
  libs/app/recommend/feature/src/recommend.page.spec.ts
  libs/app/recommend/ui/src/diet-preference-pill-component/diet-preference-pill-component.component.css
  libs/app/recommend/ui/src/diet-preference-pill-component/diet-preference-pill-component.component.html
  libs/app/recommend/ui/src/diet-preference-pill-component/diet-preference-pill-component.component.spec.ts
  libs/app/recommend/ui/src/diet-preference-pill-component/diet-preference-pill-component.component.ts
  libs/app/recommend/ui/src/item-edit-step/item-edit-step.html
  libs/app/recommend/ui/src/item-edit-step/item-edit-step.spec.ts
  libs/app/recommend/ui/src/item-edit-step/item-edit-step.ts
  libs/app/recommend/ui/src/recipe-list-step/recipe-list-step.html
  libs/app/recommend/ui/src/recipe-list-step/recipe-list-step.spec.ts
  libs/app/recommend/ui/src/recipe-list-step/recipe-list-step.ts
  libs/app/recommend/ui/src/recipe-preferences-step/recipe-preferences-step.html
  libs/app/recommend/ui/src/recipe-preferences-step/recipe-preferences-step.spec.ts
  libs/app/recommend/ui/src/recipe-preferences-step/recipe-preferences-step.ts
  libs/app/recommend/ui/src/recommend.module.ts
  libs/app/recommend/ui/src/stepper-form/steper-form.spec.ts
Labels: enhancement, backend, database

#109 Update README.md
  README.md
Labels: documentation

#107 Feat/recipe detail
  apps/api/src/main/java/com/fridgetoplate/api/IngredientController.java
  apps/api/src/main/java/com/fridgetoplate/api/PreferenceController.java
  apps/api/src/main/java/com/fridgetoplate/api/ProfileController.java
  apps/api/src/main/java/com/fridgetoplate/api/RecipeController.java
  apps/api/src/main/java/com/fridgetoplate/model/Recipe.java
  apps/api/src/main/java/com/fridgetoplate/model/RecipeStep.java
  apps/api/src/main/java/com/fridgetoplate/utils/RecipeStepArrayConverter.java
  libs/app/create/feature/src/create.page.html
  libs/app/create/feature/src/create.page.ts
  libs/app/ingredient/utils/src/interfaces/ingredient.interface.ts
  libs/app/models/api.response.ts
  libs/app/recipe/data-access/src/index.ts
  libs/app/recipe/data-access/src/mock-data/index.ts
  libs/app/recipe/data-access/src/mock-data/mock-recipe-data.ts
  libs/app/recipe/data-access/src/recipe.api.ts
  libs/app/recipe/feature/src/lib/recipe-error/recipe-error.component.css
  libs/app/recipe/feature/src/lib/recipe-error/recipe-error.component.html
  libs/app/recipe/feature/src/lib/recipe-error/recipe-error.component.spec.ts
  libs/app/recipe/feature/src/lib/recipe-error/recipe-error.component.ts
  libs/app/recipe/feature/src/recipe.page.html
  libs/app/recipe/feature/src/recipe.page.spec.ts
  libs/app/recipe/feature/src/recipe.page.ts
  libs/app/recipe/feature/src/recipe.routing.ts
  libs/app/recipe/ui/src/recipe-card/recipe-card.component.html
  libs/app/recipe/ui/src/recipe-card/recipe-card.component.spec.ts
  libs/app/recipe/utils/src/interfaces/recipe-step.interface.ts
  libs/app/recipe/utils/src/interfaces/recipe.interface.ts
  libs/app/recommend/data-access/src/index.ts
  libs/app/recommend/data-access/src/recipes.mock.ts
  libs/app/recommend/data-access/src/recommend.api.ts
  libs/app/recommend/data-access/src/store.state.ts
  libs/app/recommend/ui/src/item-edit-step/item-edit-step.ts
  libs/app/shared/api.routes.ts
  package-lock.json
Labels: enhancement, backend, database
