Repository COS301-SE-2023/FridgeToPlate, pull requests merged in 2023-07, with the labels that each got.

#121 Workflows patch
  .github/workflows/ci-dev.yml
  .github/workflows/ci-prod.yml
  package.json
Labels: dev-ops

#117 ♻️(app) replaced id with recipeId
  .github/workflows/ci-dev.yml
  apps/api/src/main/java/com/fridgetoplate/api/IngredientController.java
  apps/api/src/main/java/com/fridgetoplate/api/PreferenceController.java
  apps/api/src/main/java/com/fridgetoplate/api/ProfileController.java
  apps/api/src/main/java/com/fridgetoplate/api/RecipeController.java
  apps/api/src/main/java/com/fridgetoplate/api/RecommendController.java
  apps/api/src/main/java/com/fridgetoplate/model/Recipe.java
  apps/api/src/main/java/com/fridgetoplate/model/RecipeStep.java
  apps/api/src/main/java/com/fridgetoplate/repository/IngredientRepository.java
  apps/app-e2e/src/e2e/app.cy.ts
  apps/app/cypress/e2e/app.cy.ts
  apps/app/project.json
  libs/app/create/feature/src/create.module.ts
  libs/app/create/feature/src/create.page.html
  libs/app/create/feature/src/create.page.spec.ts
  libs/app/create/feature/src/create.page.ts
  libs/app/create/feature/src/create.routing.ts
  libs/app/recipe/feature/src/recipe.page.spec.ts
  libs/app/recipe/feature/src/recipe.page.ts
  libs/app/recommend/ui/src/item-edit-step/item-edit-step.ts
  libs/app/recommend/ui/src/recipe-preferences-step/recipe-preferences-step.spec.ts
  libs/app/recommend/ui/src/stepper-form/steper-form.spec.ts
  package-lock.json
  package.json
  tsconfig.base.json
Labels: bug

#143 Hotfix/v0.1.0 to Dev
  .github/workflows/ci-dev.yml
  .github/workflows/ci-prod.yml
  README.md
  apps/api/src/main/java/com/fridgetoplate/api/IngredientController.java
  apps/api/src/main/java/com/fridgetoplate/api/PreferenceController.java
  apps/api/src/main/java/com/fridgetoplate/api/ProfileController.java
  apps/api/src/main/java/com/fridgetoplate/api/RecipeController.java
  apps/api/src/main/java/com/fridgetoplate/api/RecommendController.java
  apps/api/src/main/java/com/fridgetoplate/model/Recipe.java
  apps/api/src/main/java/com/fridgetoplate/model/RecipeStep.java
  apps/api/src/main/java/com/fridgetoplate/repository/IngredientRepository.java
  apps/app-e2e/src/e2e/app.cy.ts
  apps/app-e2e/src/fixtures/user-details.json
  apps/app/.eslintrc.json
  apps/app/cypress.config.ts
  apps/app/cypress/e2e/app.cy.ts
  apps/app/cypress/fixtures/example.json
  apps/app/cypress/support/app.po.ts
  apps/app/cypress/support/commands.ts
  apps/app/cypress/support/e2e.ts
  apps/app/project.json
  apps/app/tsconfig.cy.json
  apps/app/tsconfig.json
  cypress.config.ts
  cypress/e2e/test-spec.cy.ts
  cypress/fixtures/example.json
  cypress/support/commands.ts
  cypress/support/e2e.ts
  libs/app/create/feature/src/create.module.ts
  libs/app/create/feature/src/create.page.html
  libs/app/create/feature/src/create.page.spec.ts
  libs/app/create/feature/src/create.page.ts
  libs/app/create/feature/src/create.routing.ts
  libs/app/recipe/feature/src/recipe.page.spec.ts
  libs/app/recipe/feature/src/recipe.page.ts
  libs/app/recommend/ui/src/item-edit-step/item-edit-step.ts
  libs/app/recommend/ui/src/recipe-preferences-step/recipe-preferences-step.spec.ts
  libs/app/recommend/ui/src/stepper-form/steper-form.spec.ts
  package-lock.json
  package.json
  tsconfig.base.json
Labels: bug, frontend, backend

#148 Hotfix/v0.1.0 into Dev
  libs/app/create/feature/src/create.page.spec.ts
  libs/app/create/feature/src/create.page.ts
Labels: bug, backend

#144 Hotfix/v0.1.0 to Main
  .github/workflows/ci-dev.yml
  .github/workflows/ci-prod.yml
  apps/api/src/main/java/com/fridgetoplate/api/IngredientController.java
  apps/api/src/main/java/com/fridgetoplate/api/PreferenceController.java
  apps/api/src/main/java/com/fridgetoplate/api/ProfileController.java
  apps/api/src/main/java/com/fridgetoplate/api/RecipeController.java
  apps/api/src/main/java/com/fridgetoplate/api/RecommendController.java
  apps/api/src/main/java/com/fridgetoplate/model/Recipe.java
  apps/api/src/main/java/com/fridgetoplate/model/RecipeStep.java
  apps/api/src/main/java/com/fridgetoplate/repository/IngredientRepository.java
  apps/app-e2e/src/e2e/app.cy.ts
  apps/app-e2e/src/fixtures/user-details.json
  apps/app/.eslintrc.json
  apps/app/cypress.config.ts
  apps/app/cypress/e2e/app.cy.ts
  apps/app/cypress/fixtures/example.json
  apps/app/cypress/support/app.po.ts
  apps/app/cypress/support/commands.ts
  apps/app/cypress/support/e2e.ts
  apps/app/project.json
  apps/app/tsconfig.cy.json
  apps/app/tsconfig.json
  cypress.config.ts
  cypress/e2e/test-spec.cy.ts
  cypress/fixtures/example.json
  cypress/support/commands.ts
  cypress/support/e2e.ts
  libs/app/create/feature/src/create.module.ts
  libs/app/create/feature/src/create.page.html
  libs/app/create/feature/src/create.page.spec.ts
  libs/app/create/feature/src/create.page.ts
  libs/app/create/feature/src/create.routing.ts
  libs/app/recipe/feature/src/recipe.page.spec.ts
  libs/app/recipe/feature/src/recipe.page.ts
  libs/app/recommend/ui/src/item-edit-step/item-edit-step.ts
  libs/app/recommend/ui/src/recipe-preferences-step/recipe-preferences-step.spec.ts
  libs/app/recommend/ui/src/stepper-form/steper-form.spec.ts
  package-lock.json
  package.json
  tsconfig.base.json
Labels: bug, frontend, backend

#153 139 implement routing guards
  libs/app/auth/data-access/src/auth.api.spec.ts
  libs/app/auth/data-access/src/auth.api.ts
  libs/app/auth/data-access/src/auth.module.ts
  libs/app/core/src/core.routing.ts
  libs/app/core/src/guards/route-guard.service.spec.ts
  libs/app/core/src/guards/route-guard.service.ts
Labels: enhancement, frontend

#156 123 update spring boot models
  apps/api/src/main/java/com/fridgetoplate/controller/IngredientController.java
  apps/api/src/main/java/com/fridgetoplate/controller/MealPlanController.java
  apps/api/src/main/java/com/fridgetoplate/controller/PreferencesController.java
  apps/api/src/main/java/com/fridgetoplate/controller/ProfileController.java
  apps/api/src/main/java/com/fridgetoplate/controller/RecipeController.java
  apps/api/src/main/java/com/fridgetoplate/controller/RecommendController.java
  apps/api/src/main/java/com/fridgetoplate/controller/ReviewController.java
  apps/api/src/main/java/com/fridgetoplate/interfaces/MealPlan.java
  apps/api/src/main/java/com/fridgetoplate/interfaces/Profile.java
  apps/api/src/main/java/com/fridgetoplate/interfaces/Recipe.java
  apps/api/src/main/java/com/fridgetoplate/interfaces/RecipeDesc.java
  apps/api/src/main/java/com/fridgetoplate/model/Ingredient.java
  apps/api/src/main/java/com/fridgetoplate/model/MealPlanModel.java
  apps/api/src/main/java/com/fridgetoplate/model/Preference.java
  apps/api/src/main/java/com/fridgetoplate/model/Preferences.java
  apps/api/src/main/java/com/fridgetoplate/model/Profile.java
  apps/api/src/main/java/com/fridgetoplate/model/ProfileModel.java
  apps/api/src/main/java/com/fridgetoplate/model/Recipe.java
  apps/api/src/main/java/com/fridgetoplate/model/RecipeModel.java
  apps/api/src/main/java/com/fridgetoplate/model/RecipeStep.java
  apps/api/src/main/java/com/fridgetoplate/model/Review.java
  apps/api/src/main/java/com/fridgetoplate/repository/IngredientRepository.java
  apps/api/src/main/java/com/fridgetoplate/repository/MealPlanRepository.java
  apps/api/src/main/java/com/fridgetoplate/repository/PreferencesRepository.java
  apps/api/src/main/java/com/fridgetoplate/repository/ProfileRepository.java
  apps/api/src/main/java/com/fridgetoplate/repository/RecipeRepository.java
  apps/api/src/main/java/com/fridgetoplate/repository/ReviewRepository.java
  apps/api/src/main/java/com/fridgetoplate/response/MealPlanResponse.java
  apps/api/src/main/java/com/fridgetoplate/response/ProfileResponse.java
  apps/api/src/main/java/com/fridgetoplate/response/RecipeResponse.java
  apps/api/src/main/java/com/fridgetoplate/utils/RecipeArrayConverter.java
  apps/api/src/main/java/com/fridgetoplate/utils/RecipeStepArrayConverter.java
  apps/api/src/main/java/com/fridgetoplate/utils/ReviewArrayConverter.java
  apps/api/src/test/java/com/fridgetoplate/api/MealPlanModelTest.java
Labels: backend, database

#155 126 update recipe page
  libs/app/navigation/feature/src/navigation.component.scss
  libs/app/recipe/feature/src/recipe.module.ts
  libs/app/recipe/feature/src/recipe.page.html
  libs/app/review/data-access/.eslintrc.json
  libs/app/review/data-access/README.md
  libs/app/review/data-access/jest.config.ts
  libs/app/review/data-access/package.json
  libs/app/review/data-access/project.json
  libs/app/review/data-access/src/index.ts
  libs/app/review/data-access/src/review.api.ts
  libs/app/review/data-access/src/review.module.ts
  libs/app/review/data-access/src/review.spec.ts
  libs/app/review/data-access/tsconfig.json
  libs/app/review/data-access/tsconfig.lib.json
  libs/app/review/data-access/tsconfig.spec.json
  libs/app/review/feature/.eslintrc.json
  libs/app/review/feature/README.md
  libs/app/review/feature/jest.config.ts
  libs/app/review/feature/package.json
  libs/app/review/feature/project.json
  libs/app/review/feature/src/index.ts
  libs/app/review/feature/src/review.component.ts
  libs/app/review/feature/src/review.html
  libs/app/review/feature/src/review.module.ts
  libs/app/review/feature/src/review.scss
  libs/app/review/feature/src/review.spec.ts
  libs/app/review/feature/src/test-setup.ts
  libs/app/review/feature/tsconfig.json
  libs/app/review/feature/tsconfig.lib.json
  libs/app/review/feature/tsconfig.spec.json
  package-lock.json
  package.json
  tsconfig.base.json
Labels: enhancement, frontend

#161 145 update sign up to store profile
  apps/api/src/main/java/com/fridgetoplate/controller/ProfileController.java
  apps/api/src/main/java/com/fridgetoplate/repository/ProfileRepository.java
  libs/app/auth/data-access/src/auth.module.ts
  libs/app/auth/data-access/src/auth.state.ts
  libs/app/auth/data-access/src/index.ts
  libs/app/auth/utils/.eslintrc.json
  libs/app/auth/utils/README.md
  libs/app/auth/utils/jest.config.ts
  libs/app/auth/utils/project.json
  libs/app/auth/utils/src/auth.actions.ts
  libs/app/auth/utils/src/index.ts
  libs/app/auth/utils/src/test-setup.ts
  libs/app/auth/utils/tsconfig.json
  libs/app/auth/utils/tsconfig.lib.json
  libs/app/auth/utils/tsconfig.spec.json
  libs/app/core/src/core.module.ts
  libs/app/core/src/core.routing.ts
  libs/app/core/src/guards/route-guard.service.spec.ts
  libs/app/core/src/guards/route-guard.service.ts
  libs/app/error/data-access/src/error.module.ts
  libs/app/error/data-access/src/index.ts
  libs/app/login/feature/src/login.page.html
  libs/app/login/feature/src/login.page.ts
  libs/app/notifications/data-access/src/index.ts
  libs/app/notifications/data-access/src/notifications.api.ts
  libs/app/notifications/data-access/src/notifications.module.ts
  libs/app/notifications/feature/src/notification.module.ts
  libs/app/notifications/feature/src/notifications.page.spec.ts
  libs/app/notifications/feature/src/notifications.page.ts
  libs/app/notifications/utils/.eslintrc.json
  libs/app/notifications/utils/README.md
  libs/app/notifications/utils/jest.config.ts
  libs/app/notifications/utils/project.json
  libs/app/notifications/utils/src/index.ts
  libs/app/notifications/utils/src/interfaces/index.ts
  libs/app/notifications/utils/src/interfaces/notifications.interface.ts
  libs/app/notifications/utils/src/test-setup.ts
  libs/app/notifications/utils/tsconfig.json
  libs/app/notifications/utils/tsconfig.lib.json
  libs/app/notifications/utils/tsconfig.spec.json
  libs/app/preferences/data-access/src/preferences.api.ts
  libs/app/profile/data-access/src/index.ts
  libs/app/profile/data-access/src/profile.api.ts
  libs/app/profile/data-access/src/profile.state.ts
  libs/app/profile/feature/src/profile.page.html
  libs/app/profile/feature/src/profile.page.spec.ts
  libs/app/profile/ui/src/edit-modal/edit-modal.component.spec.ts
  libs/app/profile/utils/src/interfaces/profile.interface.ts
  libs/app/profile/utils/src/profile.actions.ts
  libs/app/recommend/data-access/src/recommend.api.ts
  libs/app/signup/feature/src/signup.page.html
  libs/app/signup/feature/src/signup.page.ts
  tsconfig.base.json
Labels: enhancement, frontend

#163 80 implement save recipe
  apps/api/src/main/java/com/fridgetoplate/controller/ProfileController.java
  apps/api/src/main/java/com/fridgetoplate/controller/RecipeController.java
  apps/api/src/main/java/com/fridgetoplate/controller/RecommendController.java
  apps/api/src/main/java/com/fridgetoplate/frontendmodels/MealPlanFrontendModel.java
  apps/api/src/main/java/com/fridgetoplate/frontendmodels/ProfileFrontendModel.java
  apps/api/src/main/java/com/fridgetoplate/frontendmodels/RecipeFrontendModel.java
  apps/api/src/main/java/com/fridgetoplate/repository/ProfileRepository.java
  apps/api/src/main/java/com/fridgetoplate/repository/RecipeRepository.java
  libs/app/auth/data-access/src/auth.state.ts
  libs/app/auth/utils/src/auth.actions.ts
  libs/app/core/src/core.module.ts
  libs/app/core/src/core.routing.ts
  libs/app/error/data-access/src/error.state.ts
  libs/app/profile/data-access/src/profile.api.ts
  libs/app/profile/data-access/src/profile.state.ts
  libs/app/profile/feature/src/profile.page.html
  libs/app/profile/feature/src/profile.page.spec.ts
  libs/app/profile/feature/src/profile.page.ts
  libs/app/profile/ui/src/settings-modal/settings-modal.component.html
  libs/app/profile/ui/src/settings-modal/settings-modal.component.spec.ts
  libs/app/profile/ui/src/settings-modal/settings-modal.component.ts
  libs/app/profile/utils/src/profile.actions.ts
  libs/app/recipe/feature/src/recipe.page.spec.ts
  libs/app/recipe/ui/src/recipe-card/recipe-card.component.html
  libs/app/recipe/ui/src/recipe-card/recipe-card.component.spec.ts
  libs/app/recipe/ui/src/recipe-card/recipe-card.component.ts
  libs/app/recipe/ui/src/recipe.module.ts
  libs/app/recommend/feature/src/recommend.page.spec.ts
  libs/app/recommend/ui/src/diet-preference-pill-component/diet-preference-pill-component.component.spec.ts
  libs/app/recommend/ui/src/item-edit-step/item-edit-step.spec.ts
  libs/app/recommend/ui/src/recipe-list-step/recipe-list-step.spec.ts
  libs/app/recommend/ui/src/recipe-preferences-step/recipe-preferences-step.spec.ts
  libs/app/recommend/ui/src/stepper-form/steper-form.spec.ts
  libs/app/undo/data-access/.eslintrc.json
  libs/app/undo/data-access/README.md
  libs/app/undo/data-access/jest.config.ts
  libs/app/undo/data-access/project.json
  libs/app/undo/data-access/src/index.ts
  libs/app/undo/data-access/src/test-setup.ts
  libs/app/undo/data-access/src/undo.state.ts
  libs/app/undo/data-access/tsconfig.json
  libs/app/undo/data-access/tsconfig.lib.json
  libs/app/undo/data-access/tsconfig.spec.json
  libs/app/undo/utils/.eslintrc.json
  libs/app/undo/utils/README.md
  libs/app/undo/utils/jest.config.ts
  libs/app/undo/utils/project.json
  libs/app/undo/utils/src/index.ts
  libs/app/undo/utils/src/test-setup.ts
  libs/app/undo/utils/src/undo.actions.ts
  libs/app/undo/utils/tsconfig.json
  libs/app/undo/utils/tsconfig.lib.json
  libs/app/undo/utils/tsconfig.spec.json
  tsconfig.base.json
Labels: enhancement, frontend

#162 Refactor create to use ngxs
  apps/api/src/main/java/com/fridgetoplate/controller/RecipeController.java
  apps/api/src/main/java/com/fridgetoplate/model/Ingredient.java
  libs/app/create/data-access/src/create.api.ts
  libs/app/create/data-access/src/create.state.ts
  libs/app/create/feature/src/create.module.ts
  libs/app/create/feature/src/create.page.html
  libs/app/create/feature/src/create.page.spec.ts
  libs/app/create/feature/src/create.page.ts
  libs/app/profile/feature/src/profile.module.ts
  libs/app/profile/feature/src/profile.page.ts
Labels: enhancement, frontend

#171 132 implement user settings
  apps/api/src/main/java/com/fridgetoplate/controller/PreferencesController.java
  apps/api/src/main/java/com/fridgetoplate/model/Preferences.java
  apps/api/src/main/java/com/fridgetoplate/repository/PreferencesRepository.java
  apps/api/src/main/java/com/fridgetoplate/repository/ProfileRepository.java
  libs/app/auth/data-access/src/auth.state.ts
  libs/app/preferences/data-access/src/preferences.api.ts
  libs/app/preferences/data-access/src/preferences.state.ts
  libs/app/preferences/utils/src/preferences.actions.ts
  libs/app/profile/feature/src/profile.page.ts
  libs/app/profile/ui/src/settings-modal/settings-modal.component.ts
Labels: enhancement, frontend, backend, database

#168 Notifications ngxs refactor
  libs/app/core/src/core.routing.ts
  libs/app/notifications/data-access/src/index.ts
  libs/app/notifications/data-access/src/notifications.api.ts
  libs/app/notifications/data-access/src/notifications.module.ts
  libs/app/notifications/data-access/src/notifications.state.ts
  libs/app/notifications/feature/src/notification.module.ts
  libs/app/notifications/feature/src/notifications.page.html
  libs/app/notifications/feature/src/notifications.page.spec.ts
  libs/app/notifications/feature/src/notifications.page.ts
  libs/app/notifications/ui/src/tab/tab.component.html
  libs/app/notifications/utils/notifications.actions.ts
  libs/app/notifications/utils/src/interfaces/notifications.interface.ts
  libs/app/profile/feature/src/profile.page.spec.ts
Labels: enhancement, frontend

#159 133 update navbar
  libs/app/core/src/core.module.ts
  libs/app/core/src/core.shell.html
  libs/app/create/feature/src/create.page.html
  libs/app/create/feature/src/create.page.ts
  libs/app/navigation/feature/src/app-navigation-feature.spec.ts
  libs/app/navigation/feature/src/app-navigation-feature.ts
  libs/app/navigation/feature/src/navigation.component.html
  libs/app/navigation/feature/src/navigation.component.scss
  libs/app/navigation/feature/src/navigation.component.ts
  libs/app/notifications/feature/src/notification.module.ts
  libs/app/notifications/feature/src/notifications.page.html
  libs/app/profile/feature/src/index.ts
  libs/app/profile/feature/src/profile.module.ts
  libs/app/profile/feature/src/profile.page.html
  libs/app/profile/feature/src/profile.page.spec.ts
  libs/app/recipe/feature/src/recipe.page.html
  libs/app/recipe/ui/src/index.ts
  libs/app/recommend/feature/src/recommend.page.html
Labels: enhancement, design, frontend

#176 140 implement change password
  libs/app/auth/data-access/src/auth.state.ts
  libs/app/auth/utils/src/auth.actions.ts
  libs/app/profile/ui/src/password-modal/password-modal.component.html
  libs/app/profile/ui/src/password-modal/password-modal.component.scss
  libs/app/profile/ui/src/password-modal/password-modal.component.spec.ts
  libs/app/profile/ui/src/password-modal/password-modal.component.ts
  libs/app/profile/ui/src/profile.module.ts
  libs/app/profile/ui/src/settings-modal/settings-modal.component.html
  libs/app/profile/ui/src/settings-modal/settings-modal.component.spec.ts
  libs/app/profile/ui/src/settings-modal/settings-modal.component.ts
Labels: enhancement, frontend

#174 127 implement review functionality
  apps/api/src/main/java/com/fridgetoplate/controller/ReviewController.java
  apps/api/src/main/java/com/fridgetoplate/repository/ReviewRepository.java
  libs/app/edit-recipe/feature/src/edit-recipe.page.ts
  libs/app/profile/data-access/src/profile.state.ts
  libs/app/recipe/data-access/src/recipe.actions.ts
  libs/app/recipe/data-access/src/recipe.api.ts
  libs/app/recipe/data-access/src/recipe.module.ts
  libs/app/recipe/data-access/src/recipe.state.ts
  libs/app/recipe/feature/src/recipe.module.ts
  libs/app/recipe/feature/src/recipe.page.html
  libs/app/recipe/feature/src/recipe.page.spec.ts
  libs/app/recipe/feature/src/recipe.page.ts
  libs/app/recipe/utils/src/recipe.actions.ts
  libs/app/review/data-access/.eslintrc.json
  libs/app/review/data-access/README.md
  libs/app/review/data-access/jest.config.ts
  libs/app/review/data-access/package.json
  libs/app/review/data-access/project.json
  libs/app/review/data-access/src/index.ts
  libs/app/review/data-access/src/review.api.ts
  libs/app/review/data-access/src/review.module.ts
  libs/app/review/data-access/src/review.spec.ts
  libs/app/review/data-access/tsconfig.json
  libs/app/review/data-access/tsconfig.lib.json
  libs/app/review/data-access/tsconfig.spec.json
  libs/app/review/feature/project.json
  libs/app/review/feature/src/review.component.ts
  libs/app/review/feature/src/review.html
  libs/app/review/feature/src/review.scss
  libs/app/review/feature/src/review.spec.ts
  libs/app/review/feature/tsconfig.json
  libs/app/review/feature/tsconfig.lib.json
  libs/app/review/feature/tsconfig.spec.json
Labels: enhancement, frontend, backend, database

#180 177 refactor auth guards
  libs/app/auth/data-access/src/auth.api.spec.ts
  libs/app/auth/data-access/src/auth.api.ts
  libs/app/auth/data-access/src/auth.state.ts
  libs/app/auth/data-access/src/index.ts
  libs/app/core/src/core.routing.ts
  libs/app/core/src/guards/route-guard.service.spec.ts
  libs/app/core/src/guards/route-guard.service.ts
  libs/app/meal-plan/data-access/src/index.ts
  libs/app/meal-plan/data-access/src/meal-plan.api.ts
  libs/app/meal-plan/data-access/src/meal-plan.module.ts
  libs/app/meal-plan/data-access/src/meal-plan.state.ts
  libs/app/meal-plan/utils/src/index.ts
  libs/app/meal-plan/utils/src/meal-plan.actions.ts
  libs/app/profile/data-access/src/profile.module.ts
  libs/app/profile/data-access/src/profile.state.ts
  libs/app/profile/feature/src/profile.page.spec.ts
  libs/app/profile/utils/src/profile.actions.ts
  libs/app/recipe/ui/src/index.ts
  libs/app/recipe/ui/src/meal-plan-modal/meal-plan-modal.component.html
  libs/app/recipe/ui/src/meal-plan-modal/meal-plan-modal.component.scss
  libs/app/recipe/ui/src/meal-plan-modal/meal-plan-modal.component.spec.ts
  libs/app/recipe/ui/src/meal-plan-modal/meal-plan-modal.component.ts
  libs/app/recipe/ui/src/recipe-card/recipe-card.component.html
  libs/app/recipe/ui/src/recipe-card/recipe-card.component.spec.ts
  libs/app/recipe/ui/src/recipe-card/recipe-card.component.ts
  libs/app/recipe/ui/src/recipe.module.ts
  libs/app/unauthorised/feature/.eslintrc.json
  libs/app/unauthorised/feature/README.md
  libs/app/unauthorised/feature/jest.config.ts
  libs/app/unauthorised/feature/project.json
  libs/app/unauthorised/feature/src/index.ts
  libs/app/unauthorised/feature/src/test-setup.ts
  libs/app/unauthorised/feature/src/unauthorised.module.ts
  libs/app/unauthorised/feature/src/unauthorised.page.html
  libs/app/unauthorised/feature/src/unauthorised.page.scss
  libs/app/unauthorised/feature/src/unauthorised.page.spec.ts
  libs/app/unauthorised/feature/src/unauthorised.page.ts
  libs/app/unauthorised/feature/src/unauthorised.routing.ts
  libs/app/unauthorised/feature/tsconfig.json
  libs/app/unauthorised/feature/tsconfig.lib.json
  libs/app/unauthorised/feature/tsconfig.spec.json
  tsconfig.base.json
Labels: enhancement, frontend

#183 150 update and add cypress test
  .github/workflows/ci-dev.yml
  .github/workflows/ci-prod.yml
  apps/app-e2e/cypress/downloads/downloads.html
  apps/app-e2e/src/e2e/app.cy.ts
  apps/app-e2e/src/fixtures/recipe-details.json
  apps/app-e2e/src/support/commands.ts
  libs/app/create/feature/src/create.page.spec.ts
  libs/app/create/feature/src/create.page.ts
  libs/app/login/feature/src/login.page.ts
  libs/app/login/ui/.eslintrc.json
  libs/app/login/ui/README.md
  libs/app/login/ui/jest.config.ts
  libs/app/login/ui/project.json
  libs/app/login/ui/src/forgot-modal/forgot-modal.component.html
  libs/app/login/ui/src/forgot-modal/forgot-modal.component.scss
  libs/app/login/ui/src/forgot-modal/forgot-modal.component.ts
  libs/app/login/ui/src/index.ts
  libs/app/login/ui/src/login.module.ts
  libs/app/login/ui/src/test-setup.ts
  libs/app/login/ui/tsconfig.json
  libs/app/login/ui/tsconfig.lib.json
  libs/app/login/ui/tsconfig.spec.json
  libs/app/login/utils/.eslintrc.json
  libs/app/login/utils/README.md
  libs/app/login/utils/jest.config.ts
  libs/app/login/utils/project.json
  libs/app/login/utils/src/index.ts
  libs/app/login/utils/src/test-setup.ts
  libs/app/login/utils/tsconfig.json
  libs/app/login/utils/tsconfig.lib.json
  libs/app/login/utils/tsconfig.spec.json
  libs/app/profile/feature/src/profile.page.html
  libs/app/profile/ui/src/edit-modal/edit-modal.component.html
  libs/app/profile/ui/src/settings-modal/settings-modal.component.html
  libs/app/recipe/feature/src/recipe.page.html
  package-lock.json
  package.json
  tsconfig.base.json
Labels: bug, frontend

#181 129 implement notifications
  apps/api/src/main/java/com/fridgetoplate/controller/NotificationController.java
  apps/api/src/main/java/com/fridgetoplate/frontendmodels/NotificationsResponseModel.java
  apps/api/src/main/java/com/fridgetoplate/interfaces/Notification.java
  apps/api/src/main/java/com/fridgetoplate/model/NotificationModel.java
  apps/api/src/main/java/com/fridgetoplate/repository/NotificationsRepository.java
  libs/app/notifications/data-access/src/notifications.api.ts
  libs/app/notifications/data-access/src/notifications.state.ts
  libs/app/notifications/feature/src/notifications.page.spec.ts
  libs/app/notifications/feature/src/notifications.page.ts
  libs/app/review/feature/src/review.spec.ts
Labels: frontend, backend

#185 👷 (app) Updated Workflows for New Account
  .github/workflows/cd-dev.yml
  .github/workflows/cd-prod.yml
Labels: dev-ops

#187 164 refactor api
  apps/api/src/main/java/com/fridgetoplate/controller/IngredientController.java
  apps/api/src/main/java/com/fridgetoplate/controller/MealPlanController.java
  apps/api/src/main/java/com/fridgetoplate/controller/ProfileController.java
  apps/api/src/main/java/com/fridgetoplate/controller/RecipeController.java
  apps/api/src/main/java/com/fridgetoplate/controller/RecommendController.java
  apps/api/src/main/java/com/fridgetoplate/frontendmodels/MealPlanFrontendModel.java
  apps/api/src/main/java/com/fridgetoplate/frontendmodels/ProfileFrontendModel.java
  apps/api/src/main/java/com/fridgetoplate/frontendmodels/RecipeFrontendModel.java
  apps/api/src/main/java/com/fridgetoplate/interfaces/Profile.java
  apps/api/src/main/java/com/fridgetoplate/interfaces/Recipe.java
  apps/api/src/main/java/com/fridgetoplate/interfaces/RecipeDesc.java
  apps/api/src/main/java/com/fridgetoplate/model/Ingredient.java
  apps/api/src/main/java/com/fridgetoplate/model/MealPlanModel.java
  apps/api/src/main/java/com/fridgetoplate/model/ProfileModel.java
  apps/api/src/main/java/com/fridgetoplate/model/RecipePreferences.java
  apps/api/src/main/java/com/fridgetoplate/model/RecommendModel.java
  apps/api/src/main/java/com/fridgetoplate/repository/IngredientRepository.java
  apps/api/src/main/java/com/fridgetoplate/repository/MealPlanRepository.java
  apps/api/src/main/java/com/fridgetoplate/repository/ProfileRepository.java
  apps/api/src/main/java/com/fridgetoplate/repository/RecommendRepository.java
  apps/api/src/main/java/com/fridgetoplate/repository/ReviewRepository.java
  apps/api/src/test/java/com/fridgetoplate/api/MealPlanModelTest.java
  libs/app/create/feature/src/create.page.html
  libs/app/create/feature/src/create.page.spec.ts
  libs/app/create/feature/src/create.page.ts
  libs/app/edit-recipe/feature/src/edit-recipe.page.html
  libs/app/edit-recipe/feature/src/edit-recipe.page.spec.ts
  libs/app/edit-recipe/feature/src/edit-recipe.page.ts
  libs/app/meal-plan/data-access/.eslintrc.json
  libs/app/meal-plan/data-access/README.md
  libs/app/meal-plan/data-access/jest.config.ts
  libs/app/meal-plan/data-access/project.json
  libs/app/meal-plan/data-access/src/test-setup.ts
  libs/app/meal-plan/data-access/tsconfig.json
  libs/app/meal-plan/data-access/tsconfig.lib.json
  libs/app/meal-plan/data-access/tsconfig.spec.json
  libs/app/profile/data-access/src/profile.api.ts
  libs/app/profile/data-access/src/profile.state.ts
  libs/app/profile/utils/src/profile.actions.ts
  libs/app/recipe/data-access/src/recipe.state.ts
  libs/app/recipe/ui/src/recipe.module.ts
  package-lock.json
  package.json
Labels: backend, database

#186 160 add external api
  .gitignore
  apps/api/src/main/java/com/fridgetoplate/api/ApiApplication.java
  apps/api/src/main/java/com/fridgetoplate/controller/RecipeController.java
  apps/api/src/main/java/com/fridgetoplate/controller/RecommendController.java
  apps/api/src/main/java/com/fridgetoplate/frontendmodels/RecipePreferencesFrontendModel.java
  apps/api/src/main/java/com/fridgetoplate/frontendmodels/RecommendFrontendModel.java
  apps/api/src/main/java/com/fridgetoplate/interfaces/Difficulty.java
  apps/api/src/main/java/com/fridgetoplate/interfaces/Meal.java
  apps/api/src/main/java/com/fridgetoplate/interfaces/SpoonacularAnalyzedInstruction.java
  apps/api/src/main/java/com/fridgetoplate/interfaces/SpoonacularEquipment.java
  apps/api/src/main/java/com/fridgetoplate/interfaces/SpoonacularIngredient.java
  apps/api/src/main/java/com/fridgetoplate/interfaces/SpoonacularLength.java
  apps/api/src/main/java/com/fridgetoplate/interfaces/SpoonacularRecipe.java
  apps/api/src/main/java/com/fridgetoplate/interfaces/SpoonacularResponse.java
  apps/api/src/main/java/com/fridgetoplate/interfaces/SpoonacularStep.java
  apps/api/src/main/java/com/fridgetoplate/repository/RecipeRepository.java
  apps/api/src/main/java/com/fridgetoplate/service/ExternalApiService.java
  apps/api/src/main/java/com/fridgetoplate/utils/SpoonacularMiscUtils.java
  apps/api/src/main/java/com/fridgetoplate/utils/SpoonacularRecipeConverter.java
  libs/app/notifications/ui/src/tab/tab.component.spec.ts
  libs/app/profile/ui/src/edit-modal/edit-modal.component.spec.ts
  libs/app/profile/ui/src/password-modal/password-modal.component.spec.ts
  libs/app/recommend/ui/src/stepper-form/steper-form.spec.ts
  libs/app/review/feature/src/review.spec.ts
Labels: enhancement, backend, database

#195 188 bug cursor click sign up and login
  libs/app/login/feature/src/login.page.html
  libs/app/profile/data-access/src/profile.state.ts
  libs/app/recipe/ui/src/recipe-card/recipe-card.component.html
  libs/app/signup/feature/src/signup.page.html
Labels: bug, frontend

#198 🐛 (app) Fixed Testing Bug
  libs/app/profile/data-access/src/profile.state.ts
Labels: bug, frontend

#201 BUG: Update Profile
  apps/api/src/main/java/com/fridgetoplate/repository/ProfileRepository.java
Labels: bug, backend

#202 199 bug create using localhost
  apps/api/src/main/java/com/fridgetoplate/repository/RecipeRepository.java
  apps/app-e2e/src/e2e/app.cy.ts
  libs/app/create/feature/src/create.page.ts
  libs/app/profile/data-access/src/profile.api.ts
  libs/app/profile/data-access/src/profile.state.ts
  libs/app/profile/utils/src/profile.actions.ts
  libs/app/recipe/data-access/src/recipe.actions.ts
  libs/app/recipe/data-access/src/recipe.api.ts
  libs/app/recipe/data-access/src/recipe.state.ts
  libs/app/recipe/feature/src/recipe.page.ts
  libs/app/recipe/ui/src/recipe-card/recipe-card.component.html
  libs/app/review/feature/src/review.component.ts
Labels: bug, frontend, backend

#204 125 home page
  libs/app/core/src/core.routing.ts
  libs/app/home/feature/.eslintrc.json
  libs/app/home/feature/README.md
  libs/app/home/feature/jest.config.ts
  libs/app/home/feature/project.json
  libs/app/home/feature/src/home.module.ts
  libs/app/home/feature/src/home.page.css
  libs/app/home/feature/src/home.page.html
  libs/app/home/feature/src/home.page.spec.ts
  libs/app/home/feature/src/home.page.ts
  libs/app/home/feature/src/home.routing.ts
  libs/app/home/feature/src/index.ts
  libs/app/home/feature/src/test-setup.ts
  libs/app/home/feature/tsconfig.json
  libs/app/home/feature/tsconfig.lib.json
  libs/app/home/feature/tsconfig.spec.json
  libs/app/navigation/feature/src/navigation.component.html
  libs/app/navigation/feature/src/navigation.component.ts
  libs/app/recipe/data-access/src/recipe.state.ts
  tsconfig.base.json
Labels: enhancement, frontend, backend

#210 🐛 (app) Fixed Styling Error
  apps/api/src/main/java/com/fridgetoplate/controller/MealPlanController.java
  apps/api/src/main/java/com/fridgetoplate/repository/ProfileRepository.java
  libs/app/home/feature/src/home.page.html
  libs/app/navigation/feature/package.json
  libs/app/navigation/feature/project.json
  libs/app/navigation/feature/src/navigation.component.html
  libs/app/navigation/feature/src/navigation.component.ts
  libs/app/profile/feature/src/profile.page.html
Labels: bug, frontend

#211 194 incorrect recommend proceedure
  apps/api/src/main/java/com/fridgetoplate/controller/RecommendController.java
  apps/api/src/main/java/com/fridgetoplate/frontendmodels/RecipePreferencesFrontendModel.java
  apps/api/src/main/java/com/fridgetoplate/frontendmodels/RecommendFrontendModel.java
  apps/api/src/main/java/com/fridgetoplate/interfaces/RecipePreferences.java
  apps/api/src/main/java/com/fridgetoplate/interfaces/Recommend.java
  apps/api/src/main/java/com/fridgetoplate/model/RecommendModel.java
  apps/api/src/main/java/com/fridgetoplate/repository/RecipeRepository.java
  apps/api/src/main/java/com/fridgetoplate/repository/RecommendRepository.java
  apps/api/src/main/java/com/fridgetoplate/service/ExternalApiService.java
  apps/api/src/main/java/com/fridgetoplate/utils/RecipePreferencesConverter.java
  apps/api/src/main/java/com/fridgetoplate/utils/SpoonacularMiscUtils.java
  apps/api/src/main/java/com/fridgetoplate/utils/SpoonacularRecipeConverter.java
  libs/app/auth/data-access/src/auth.state.ts
  libs/app/login/feature/src/login.page.html
  libs/app/profile/utils/src/profile.actions.ts
  libs/app/recommend/data-access/src/recommend.api.ts
  libs/app/recommend/data-access/src/recommend.state.ts
  libs/app/recommend/feature/src/recommend.page.ts
  libs/app/recommend/ui/src/recipe-list-step/recipe-list-step.html
  libs/app/recommend/ui/src/recipe-list-step/recipe-list-step.ts
  libs/app/recommend/ui/src/stepper-form/steper-form.spec.ts
  libs/app/recommend/ui/src/stepper-form/stepper-form.html
  libs/app/recommend/ui/src/stepper-form/stepper-form.ts
  libs/app/recommend/utils/src/recommend.actions.ts
  libs/app/signup/feature/src/signup.page.html
Labels: frontend, backend

#206 📝 (workspace) ReadMe Updated
  README.md
Labels: documentation

#219 203 bug recipe page still shows if error or empty
  apps/app-e2e/src/e2e/app.cy.ts
  libs/app/core/src/core.module.ts
  libs/app/core/src/core.routing.ts
  libs/app/edit-recipe/data-access/.eslintrc.json
  libs/app/edit-recipe/data-access/README.md
  libs/app/edit-recipe/data-access/jest.config.ts
  libs/app/edit-recipe/data-access/project.json
  libs/app/edit-recipe/data-access/src/edit-recipe.module.ts
  libs/app/edit-recipe/data-access/src/edit-recipe.state.ts
  libs/app/edit-recipe/data-access/src/index.ts
  libs/app/edit-recipe/data-access/src/test-setup.ts
  libs/app/edit-recipe/data-access/tsconfig.json
  libs/app/edit-recipe/data-access/tsconfig.lib.json
  libs/app/edit-recipe/data-access/tsconfig.spec.json
  libs/app/edit-recipe/feature/src/edit-recipe.module.ts
  libs/app/edit-recipe/feature/src/edit-recipe.page.html
  libs/app/edit-recipe/feature/src/edit-recipe.page.spec.ts
  libs/app/edit-recipe/feature/src/edit-recipe.page.ts
  libs/app/edit-recipe/utils/.eslintrc.json
  libs/app/edit-recipe/utils/README.md
  libs/app/edit-recipe/utils/jest.config.ts
  libs/app/edit-recipe/utils/project.json
  libs/app/edit-recipe/utils/src/edit-recipe.actions.ts
  libs/app/edit-recipe/utils/src/edit-recipe.module.ts
  libs/app/edit-recipe/utils/src/index.ts
  libs/app/edit-recipe/utils/src/test-setup.ts
  libs/app/edit-recipe/utils/tsconfig.json
  libs/app/edit-recipe/utils/tsconfig.lib.json
  libs/app/edit-recipe/utils/tsconfig.spec.json
  libs/app/navigation/feature/src/navigation.component.ts
  libs/app/recipe/data-access/src/recipe.state.ts
  libs/app/recipe/feature/src/recipe.page.html
  libs/app/recipe/feature/src/recipe.page.spec.ts
  libs/app/recipe/feature/src/recipe.page.ts
  libs/app/recipe/ui/src/recipe-card/recipe-card.component.spec.ts
  libs/app/recipe/ui/src/recipe-card/recipe-card.component.ts
  libs/app/recipe/ui/src/recipe.module.ts
  libs/app/recommend/data-access/src/recommend.state.ts
  package-lock.json
  package.json
  tsconfig.base.json
Labels: bug, frontend

#224 216 recommend api 500 error
  apps/api/src/main/java/com/fridgetoplate/controller/RecommendController.java
Labels: bug, backend

#223 208 bug featured recipes retrieval
  apps/api/src/main/java/com/fridgetoplate/controller/RecipeController.java
  apps/app-e2e/src/e2e/app.cy.ts
  libs/app/auth/data-access/src/auth.state.ts
  libs/app/core/src/core.module.ts
  libs/app/core/src/core.routing.ts
  libs/app/explore/data-access/src/explore.api.ts
  libs/app/explore/data-access/src/index.ts
  libs/app/explore/feature/src/explore.page.html
  libs/app/explore/feature/src/explore.page.ts
  libs/app/explore/ui/src/explore-card/explore-card.component.html
  libs/app/explore/ui/src/searching-modal/searching-modal.component.html
  libs/app/explore/utils/src/interfaces/explore.interface.ts
  libs/app/home/data-access/.eslintrc.json
  libs/app/home/data-access/README.md
  libs/app/home/data-access/jest.config.ts
  libs/app/home/data-access/project.json
  libs/app/home/data-access/src/home.module.ts
  libs/app/home/data-access/src/home.state.ts
  libs/app/home/data-access/src/index.ts
  libs/app/home/data-access/src/test-setup.ts
  libs/app/home/data-access/tsconfig.json
  libs/app/home/data-access/tsconfig.lib.json
  libs/app/home/data-access/tsconfig.spec.json
  libs/app/home/feature/src/home.module.ts
  libs/app/home/feature/src/home.page.ts
  libs/app/home/utils/.eslintrc.json
  libs/app/home/utils/README.md
  libs/app/home/utils/jest.config.ts
  libs/app/home/utils/project.json
  libs/app/home/utils/src/home.actions.ts
  libs/app/home/utils/src/index.ts
  libs/app/home/utils/src/test-setup.ts
  libs/app/home/utils/tsconfig.json
  libs/app/home/utils/tsconfig.lib.json
  libs/app/home/utils/tsconfig.spec.json
  libs/app/login/feature/src/login.page.html
  libs/app/login/feature/src/login.page.ts
  libs/app/navigation/feature/src/navigation.component.html
  libs/app/profile/ui/src/settings-modal/settings-modal.component.ts
  libs/app/recipe/data-access/src/recipe.state.ts
  libs/app/recipe/feature/src/recipe.page.html
  libs/app/recipe/feature/src/recipe.page.spec.ts
  libs/app/recipe/ui/src/recipe-card/recipe-card.component.spec.ts
  libs/app/recipe/ui/src/recipe-card/recipe-card.component.ts
  libs/app/recipe/utils/src/recipe.actions.ts
  libs/app/recommend/data-access/src/recommend.state.ts
  libs/app/recommend/utils/src/recommend.actions.ts
  libs/app/review/feature/src/review.component.ts
  tsconfig.base.json
Labels: bug, frontend, backend
