Repository COS301-SE-2023/FridgeToPlate, pull requests merged in 2023-08, with the labels that each got.

#259 fix: :bug: Fixed no units on recipe page
  apps/api/src/main/java/com/fridgetoplate/interfaces/ExtendedIngredient.java
  apps/api/src/main/java/com/fridgetoplate/interfaces/Measures.java
  apps/api/src/main/java/com/fridgetoplate/interfaces/Metric.java
  apps/api/src/main/java/com/fridgetoplate/interfaces/SpoonacularRecipe.java
  apps/api/src/main/java/com/fridgetoplate/interfaces/Us.java
  apps/api/src/main/java/com/fridgetoplate/model/Ingredient.java
  apps/api/src/main/java/com/fridgetoplate/service/ExternalApiService.java
  apps/api/src/main/java/com/fridgetoplate/utils/SpoonacularRecipeConverter.java
Labels: bug, backend

#260 242 bug user recipe picture
  libs/app/create/feature/src/create.page.spec.ts
  libs/app/create/feature/src/create.page.ts
Labels: bug, frontend

#263 249 uiux profile
  libs/app/profile/feature/src/profile.page.html
Labels: design, frontend

#265 250 uiux create
  apps/app-e2e/src/e2e/app.cy.ts
  libs/app/create/feature/src/create.page.html
  libs/app/create/feature/src/create.page.ts
  libs/app/edit-recipe/feature/src/edit-recipe.page.html
  libs/app/edit-recipe/feature/src/edit-recipe.page.ts
  libs/app/recipe/feature/src/recipe.page.html
  libs/app/recipe/ui/src/recipe-card/recipe-card.component.html
  libs/app/recipe/utils/src/interfaces/recipe.interface.ts
Labels: design, frontend

#262 254 UI/ux notifications
  libs/app/explore/feature/src/explore.page.spec.ts
  libs/app/explore/ui/src/searching-modal/searching-modal.component.spec.ts
  libs/app/notifications/feature/src/notifications.page.html
  libs/app/notifications/ui/src/tabbed/tabbed.component.html
Labels: design, frontend

#266 246 profile service refactor
  README.md
  apps/api/src/main/java/com/fridgetoplate/controller/ProfileController.java
  apps/api/src/main/java/com/fridgetoplate/controller/RecipeController.java
  apps/api/src/main/java/com/fridgetoplate/controller/RecommendController.java
  apps/api/src/main/java/com/fridgetoplate/controller/ReviewController.java
  apps/api/src/main/java/com/fridgetoplate/repository/MealPlanRepository.java
  apps/api/src/main/java/com/fridgetoplate/repository/ProfileRepository.java
  apps/api/src/main/java/com/fridgetoplate/repository/RecipeRepository.java
  apps/api/src/main/java/com/fridgetoplate/repository/ReviewRepository.java
  apps/api/src/main/java/com/fridgetoplate/service/MealPlanService.java
  apps/api/src/main/java/com/fridgetoplate/service/ProfileService.java
  apps/api/src/main/java/com/fridgetoplate/service/RecipeService.java
Labels: enhancement, backend

#267 235 barcode creation
  libs/app/environments/utils/src/environment.ts
  libs/app/recommend/data-access/src/recommend.api.ts
  libs/app/recommend/utils/src/functions/index.ts
  libs/app/recommend/utils/src/functions/recommendUtilFunctions.ts
  libs/app/recommend/utils/src/index.ts
  libs/app/recommend/utils/src/interfaces/index.ts
  libs/app/recommend/utils/src/interfaces/product-information.interface.ts
Labels: enhancement, frontend

#268 232 video embedding in recipe page
  libs/app/recipe/feature/src/recipe.page.html
  libs/app/recipe/feature/src/recipe.page.spec.ts
  libs/app/recipe/feature/src/recipe.page.ts
  libs/app/recipe/utils/src/interfaces/recipe.interface.ts
Labels: enhancement, design, frontend
